### ISSUE TITLE
WSL iA Writer support ✍

### ISSUE THREAD

**Issue by vmbruno** [jrnl-org/jrnl#1033]
I'm running jrnl on Ubuntu on Windows (with WSL2). Using the new Windows Terminal app. Jrnl is working really well with this setup.

The only thing is I can't seem to work with my external editor. Does anyone know how to use iA Writer as the external editor on WSL? It would mean launching a iA Writer on Windows from jrnl running on WSL2.
* WSL2
* iA Writer on Windows
* jrnl running on Linux

I've managed to have jrnl open iA Writer with  `editor: ' "/mnt/c/Program Files/iA Writer/iAWriter.exe" '`

When I launch jrnl it opens iA Writer and waits for the file to be saved. However, iA Writer just opens a new blank file. When I save the file, it prompts where I want to save it, and when I go back to jrnl it just says `[Nothing saved to file]`.

Any ideas on how to tell iA Writer to open the temp jrnl file?

**Comment by wren** [comment]
I'm not familiar with IA Writer, but a quick search didn't turn up their command line flags. Do you know if there's one for passing in which file you want to edit?

 Jrnl passes the name of the temp file to the editor as the only argument. So, for example, b if the flag for a file is `--file`, then you would configure your editor to be `editor: ' "/mnt/c/Program Files/iA Writer/iAWriter.exe" --file '` so it would receive the file name that jrnl is passing to it.

 Does that make sense?

**Comment by vmbruno** [comment]
Thanks for sending this. I've tried a few different obvious flags but couldn't find the one supported by the app. I've emailed the iA team let's hope they can shed some light on this one.

**Comment by vmbruno** [comment]
Ok after much trial and error I figured how to get this working, and I believe it's a jrnl bug.

In the config file I've set `editor: ' "/mnt/c/Program Files/iA Writer/iAWriter.exe" '` (with no flags set).

When I used the `jrnl` command I was in the directory `/mnt/c/Users/name/journal`. This is a folder in Windows (but remember I'm running this in WSL2). And iAWriter was opening a blank file. If I run `jrnl` while inside the root linux folder then it works. 

So it seems like something to do with either the relative path of the tmp file or the way WSL treats folders. Anyone has an idea on how to fix this?

**Comment by wren** [comment]
Ah, I see. Can you run jrnl with `--debug` and paste the output here? That would help give us a better idea of what's going on.

**Comment by micahellison** [comment]
Hi there @vmbruno, thanks for this info. We're thinking about making an enhancement to deal with this (#1037) but in the meantime, there's a workaround you can set up in your WSL environment:

* Install [wsl-path-converter](https://pypi.org/project/wsl-path-converter/).
  * I'd do it with pipx: `pipx install wsl-path-converter`. 
  * You need this to convert paths from WSL to Windows
* Change your temp dir (the TMP environment var) to somewhere within /mnt/c.
  * For instance: `export TMP=/mnt/c/Users/micah/temp`
  * You need this because the default temp path is /tmp/ and that can't be read by Windows
* Create a shell script that will launch your editor with the WPC path.
  * I think you should be able to do it with a one-liner like so:
`"/mnt/c/Program Files/iA Writer/iAWriter.exe" $(wpc -w $1)`
* Modify your jrnl config file editor field to point to your shell script

Please let me know if this works for you! Even if we don't end up implementing the enhancement, it could be useful for us to document the workaround.

**Comment by micahellison** [comment]
I'm closing this as it's a bit old. Feel free to reach out if you run into any problems with this.
