### ISSUE TITLE
Support alternative separator characters

### ISSUE THREAD

**Issue by felixonmars** [jrnl-org/jrnl#1041]
## Feature Request
I would like to add support for alternative characters as separators. It can either be static (added into the code directly) or configurable.

### Use Case/Motivation
Use jrnl for Asian languages (CJK). When an IME is in use, we have `：` instead of `:` and `。` instead of `.`

**Comment by eshrh** [comment]
I believe that it already checks for full-width 。the problem is that it needs some whitespace after the terminator to match the regex. This is to avoid things like urls mistakenly causing a sentence break. CJK usually don't have the whitespace after the terminator though, which is why it fails to detect them.

There should be a solution by matching all terminals first+whitespace and then matching the fullwidth terminals only.

I'm working on it

**Comment by felixonmars** [comment]
> I believe that it already checks for full-width 。the problem is that it needs some whitespace after the terminator to match the regex. This is to avoid things like urls mistakenly causing a sentence break. CJK usually don't have the whitespace after the terminator though, which is why it fails to detect them.
> 
> There should be a solution by matching all terminals first+whitespace and then matching the fullwidth terminals only.
> 
> I'm working on it

Indeed, it works here if I add a space afterwards. Thanks!
