### ISSUE TITLE
Is it possible to only be prompted for a password when *reading* entries?

### ISSUE THREAD

**Issue by trych** [jrnl-org/jrnl#1077]
Hi there,

I'm a new jrnl user and I like it so far, but now I was wondering:

I want to keep my journal encrypted, so others cannot read it. Therefore I also don't want to store my password in the keychain. However, I would like to allow the *adding* of new entries to work without passwords, so it becomes more convenient for me (basically, I don't need to password protect the *entering* process, just the *reading* process).

Is there any way to achieve this?

Thanks!

**Comment by micahellison** [comment]
Hi there, thanks for your question. Unfortunately, the answer is no, for now.

We might be able to implement this or something like this in the future using a GPG public key and directory-based (rather than file-based) journals, but currently we only support the use of a password to encrypt and decrypt.

**Comment by trych** [comment]
That's unfortunate, but thanks for the quick answer. :)
