### ISSUE TITLE
Add the -a flag to documentation.

### ISSUE THREAD

**Issue by Jon-zachary** [jrnl-org/jrnl#1119]
### Affected Page(s)
  - https://github.com/jrnl-org/jrnl/blob/develop/docs/usage.md

### What Could Be Better?

I think it would be useful to include the -a flag in both the usage documentation and the help info from the -h flag. It's probably not something you use that much as you use the program more but I think in the beginning it's an important command to know. I would be happy to write it up in a PR if there's any interest.

**Comment by micahellison** [comment]
Hi, thanks for the issue! The `-a` flag is really just `-and` -- it resolves to that because no other flag starts with `a` (for instance, `-an` does the same thing). While the `-h` flag is supported as an alias for `--help` because it has been around for a long time.

However, I think it's worth documenting in the "Advanced Usage" that parameters that can be shortened, and we would welcome a PR for this.

**Comment by Jon-zachary** [comment]
Ah, ok that makes sense. I stumbled on -a by accident and thought it was s shortening of --all or something like that. I thought it made sense to have 'read all the entries' flag but now I see that it's just filtering without a filter parameter so it displays everything. Thanks for clearing that up! I will look at the advanced usage docs and see if there's a good place to add in something about shortened aliases.

**Comment by tiagoboldt** [comment]
>However, I think it's worth documenting in the "Advanced Usage" that parameters that can be shortened, and we would welcome a PR for this.

@micahellison does it make sense to allow  `-a` to behave as `--and`? This breaks consistency in argument usage. For example `-l` does not work instead of `--ls`. I would prefer that they worked consistently, hence, dropping support for `-a` as it works today. What are your thoughts?

**Comment by wren** [comment]
@tiagoboldt I think I might be able to clarify the confusion here. The flag `-a` (one dash) is short for `-and` (one dash). `-l` (one dash) is not short for `--ls` (two dashes) because they have a different amount of dashes.

From [basic usage](https://jrnl.sh/en/latest/usage/#basic-usage):

> We intentionally break a convention on command line arguments: all arguments starting with a single dash (-) will filter your journal before viewing it. Filter arguments can be combined arbitrarily. Arguments with a double dash (--) will control how your journal is displayed or exported. Control arguments are mutually exclusive (i.e., you can only specify one way to display or export your journal at a time).

The only exception is `-h` (one dash) which is short for `--help` (two dashes). This is because old versions of jrnl used `-h` so we've kept it around for backward compatibility. Because of this, though, we've hidden `-h` from the help page, and will likely remove it in some future version of jrnl.
