### ISSUE TITLE
Filter for entries from the same date in previous years

### ISSUE THREAD

**Issue by DanaKirsh** [jrnl-org/jrnl#1143]
## Feature Request
Would love to be able to see what I was doing today in previous years.

### Use Case/Motivation
Facilitates reminiscing, which is a major reason many people keep a journal in the first place.

### Example Usage
``` 
jrnl -reminisce
```
Result:
```
01-07-2015 21:00 Monty Python and the Holy Grail 
@movie

01-07-2016 20:00 Family @board-games night

01-07-2019 10:00 Graduated from uni
```

Would be nice to print `(_ years ago)` for each entry as well. Maybe like this?
```
01-07-2015 21:00 (5 years ago) Monty Python and the Holy Grail 
@movie

01-07-2016 20:00 (4 years ago) Family @board-games night

01-07-2019 10:00 (1 year ago) Graduated from uni
```

**Comment by KarimPwnz** [comment]
Love it! Will be working on it today.

**Comment by wren** [comment]
This is a great idea. Thank you, @DanaKirsh! And thanks @KarimPwnz for the day/month/year addition.

I'm not sure `-reminisce` is the right name, though. All of our other search filters are descriptors for the journal or entries you are searching for (`-starred`, `-from`, `-to`, etc), and `-reminisce` would be a descriptor for what the user is doing (rather than the entries that user is searching for).

Maybe something like `-on-this-date` or `-today-in-history`? Anyone have any suggestions?

**Comment by KarimPwnz** [comment]
I am a fan of `-today-in-history`! I can modify #1145 to have that.

**Comment by wren** [comment]
I am also leaning towards `-today-in-history`. @micahellison What do you think?

**Comment by micahellison** [comment]
I am absolutely onboard with `-today-in-history` too!
