### ISSUE TITLE
add instructions to add VSCode as an external editor for Windows

### ISSUE THREAD

**Issue by dheerajdlalwani** [jrnl-org/jrnl#1155]
### Affected Page(s)

  - https://jrnl.sh/en/stable/recipes

### What Could Be Better?

I wanted to use VSCode as my external editor for jrnl. I did search online and the documentation. It lists how to set up VSCode as an external editor for MacOS and Linux but not for Windows. It would be really great if the step by step instructions for doing the same were added. Thank you :-)

### Other Information

No.

**Comment by micahellison** [comment]
Thanks for this issue! I've just got a pull request in to fix it, but in the meantime, the instructions are basically the same -- you need to add the `--wait` argument to your VS Code call, like so if it's in your PATH variable:
```
editor: 'code.exe --wait'
```
Or if it's not in your PATH, you'll need to refer to the whole path of VS Code (though this will not work until jrnl 2.7 due to bug #1096). For me that looks like:
```
editor: 'C:\Users\micah\AppData\Local\Programs\Microsoft VS Code\code.exe --wait'
```
