### ISSUE TITLE
Override (select) configuration values during invocation 

### ISSUE THREAD

**Issue by sriniv27** [jrnl-org/jrnl#1157]
### Use Case/Motivation

One that I can think of, which prompted the idea, was to be able to quickly launch a floating terminal with the built-in input prompt so I can log an entry and then Ctrl-D to exit. In my normal writing workflow I prefer to have a highly configured editor instance for writing with all the markdown bells and whistles. 

To accomplish this I propose that `jrnl` can be launched with an override option like `--override '{"editor": " "}'` that increases flexibility for specific workflows, while still preserving a configured setup for "main" writing workflows. 

### Example Usage

`jrnl --override '{"editor": " ", "linewrap": 40}'`
### Other information

I suppose this might be an orthogonal way to implement #1026 or #1068. 
I tried out a unittested prototype for this specific use-case in [my fork](https://github.com/sriniv27/jrnl), but I don't want to duplicate effort or step on anyone's toes; what are your thoughts?

**Comment by KarimPwnz** [comment]
I think this will also reduce test complexity by needing less configs (see https://github.com/jrnl-org/jrnl/issues/1068#issuecomment-761897581). In fact, unlike #1068, `--override`'s ability for temporary changes makes it ideal for testing.

**Comment by KarimPwnz** [comment]
Please do make a PR with your fork!

**Comment by sriniv27** [comment]
Cool, I'll clean up the code and tests and set up some `behave` tests for end-to-end behavior. 

I think there needs to be some discussion on what makes sense to have as runtime overrides e.g. overriding `editor`, `linewrap`, etc make sense, but not so much `encrypt` or `default`

**Comment by micahellison** [comment]
Thank you @sriniv27 for this suggestion. It's an excellent idea, and it's nice to see the well-thought-out work you've already done on it. I do have a couple notes after discussing this with @wren today:

* Since "override" is just a bit generic, and we're going to have to live with new arguments for years to come, I think the argument should be `--config-override`, which would be consistent with what we're thinking of for the new config arguments in #1068.
* The JSON slug is a cool idea, but it's not particularly consistent with the config YAML nor the notation that would make sense for addressing other command-line config features (like #1068). We think dot notation would be best, e.g. `colors.body` to modify the `body` property in the `colors` key. For multiple values, the user would have to enter `--config-override` multiple times, like so:

```
jrnl -n 5 --config-override colors.body red --config-override colors.title blue
```

**Comment by eshrh** [comment]
> Cool, I'll clean up the code and tests and set up some `behave` tests for end-to-end behavior.
> 
> I think there needs to be some discussion on what makes sense to have as runtime overrides e.g. overriding `editor`, `linewrap`, etc make sense, but not so much `encrypt` or `default`

With regards to this, I think it's fine to allow all overrides. I have found myself switching between encrypt true and false while testing quite a few times. 

Concerning the argument format, out of the options suggested, I prefer the dictionary format. This is simply because the most common uses of this idea are in scripts and automated processes; or either automated or manual testing. Being able to automatically generate a set of overrides in a regular format that is not verbose is important. 

Like you said yourself, this can be a little "less magical" than the rest of the interface. 

I wonder what you guys think of a compromise along the lines of

`--config-override '{"editor":"vim","journals.default.encrypt":"true","colors.title":"blue"}'`

because the one flaw with the dictionary system is that it would becomes impossible to modify the sub-yaml options individually without redefining EVERYTHING under the parent option.

**Comment by sriniv27** [comment]
I like the idea of naming the parameter `--config-override`, in keeping with "configuration modification" section of the command-line interface. 

I did not intend for the serialized JSON to be the final interface of the config override. I like the consistency of passing in valid YAML syntax, but I am split on how multiple overrides are to be passed. 

On the one hand, multiple `--config-override` invocations may be acceptable given that, as mentioned in #1068, these can be pretty high impact and the extra typing can be worth it to involve deliberate thought. It is extra typing though.

@eshrh's proposed syntax has merit i'e multiple arguments passed as a delimited list of key-value pairs,  but I'd be wary of nested quotes. They're a nightmare to debug for the end user, not to mention accounting for alternate shells/platforms. 

@eshrh, I disagree that all overrides should be allowed [for the end user]. Consider a configuration where by default, `encryption: false`. What would it mean when `--config-override encrypt: true` is passed? Would this encrypt a formerly unencrypted journal? Another thing to consider, at least for the encrypt flag, is that standalone runtime arguments exist to encrypt/decrypt a journal.

**Comment by eshrh** [comment]
True, I never thought about that. There's just so much flexibility in the config file itself that there are a lot of possible problems like that. Micah also mentioned the impossibility of setting a color without a journal selected. There is some error checking that needs to be implemented. I agree the nested quotes are pretty annoying.

So, here's a refined idea:

`--config-override "color.title:blue, color.body:red, editor:vim"`

This should lead to minimal difficulty in parsing because its all one argument. It should be possible to turn this into the necessary ~~nested dictionary?~~ format.

I think this is good because it only includes(but necessitates) one pair of quotes. In the multiple invocation setup, I can foresee the user having to type several pairs of quotes; consider specifying the path to a editor executable and the path to a journal. I prefer my idea because it is more consistent with the YAML format. I'm interested to hear if sriniv has some entirely different idea. 

I still stand against multiple invocations. One of the most powerful usages of this patch is for testing large changes in configs. This may involve redefining 5+ things at once, which is already a solid 85+ unnecessary characters that will likely create ugly linewraps in a script.

To simplify things, perhaps the user cannot override encryption ever. Like you said, false->true leads to some unnatural problems. true->false is also annoying because you can't do anything useful. Imagine disabling encryption, writing an unencrypted entry appended to an encrypted journal and then trying to encrypt it all again :skull_and_crossbones:. If you needed the raw encrypted text, just using `cat` seems way more suited. Maybe a custom exception is in order for this error.

Micah mentioned in the other issue that the user shouldn't be able to override with a journal selected. I think this is fine(more user freedom, but also user danger), but maybe there's a possibility of appending `journals.selectedJournal` to the key for safety purposes. Thus, the user typing

`jrnl work --config-override "journal:~/work.txt"` actually becomes `jrnl work --config-override "journals.work.journal:..." Safer because there's no chance of modifying the wrong thing and getting unexpected results. Idk, i didn't think this particular idea through, its just an idea to put out there.

**Comment by KarimPwnz** [comment]
> With regards to this, I think it's fine to allow all overrides. I have found myself switching between encrypt true and false while testing quite a few times.

I agree with @eshrh on this. There is also a note in https://jrnl.sh/en/stable/advanced/ warning against changing `encrypt`.

**Comment by wren** [comment]
There's a lot of good comments happening in here, and I don't think I'm ready to comment on all of it yet, so I'll just put a few notes for now.

**About allowing encrypt to be overriden or not**:

I think any override should be allowed for a few reasons:

1. We generally trust our users (that's why the config file isn't locked down in any way). 
2. It would be useful for support purposes. For example, we sometimes get a support request, and to help diagnose, we need to guide a user to change their config, and then remind them to change it back if it didn't pan out. It would be very nice to be able to say something like "run this command `jrnl --config-override encrypt false -3` and if that works it means your config got out of sync." (or whatever syntax we land on).
3. I believe users would come up with new use cases if we give them the tools to do so. One I can think of now, is being able to load a "secret journal" that isn't in your config. Maybe something like `jrnl --config-override '{journals: {secret_journal: {journal: "somefile.txt", encrypt: true}}}'` (or whatever syntax we land on). This could also be useful in loading other journal you don't regularly use (like during development).

**About which syntax to use to invoke multiple values**:

No matter what we land on, I want to be sure it's a commonly used syntax, and not a homegrown solution. In my opinion, homegrown solutions are always more brittle, and more work to maintain, so should be avoided unless there's a very, very good reason to do implement them.

- The dot notation is very common, and used by tools/languages like git, python, javascript, etc. The downside is that it requires invoking once per value changed (although we can allow as many as we want in one call to jrnl).
- Yaml is also obviously common, and has the advantage of being in our config file already. The downside is that it's very sensitive to whitespace, so multiple values would likely need to require linebreaks and get messy in a terminal (you can condense yaml into one line, but then it's basically json at that point).
- Json is also very common, but has a lot of extra syntax required. This can be okay for longer invocations, but is pretty kludgy when you only want to change one value. I consider the extra syntax to be generally against  the spirit of jrnl and its focus on human readability. But it is a subset of yaml, so it wouldn't really a big deal to support if yaml is already supported (most yaml parsers can parse json, too).

So, I guess I see the division as being between dot notation, and yaml/json. Maybe there's some way to support both?


**Misc**:

> This is simply because the most common uses of this idea are in scripts and automated processes; or either automated or manual testing.

I'm not sure I agree with this. These are definitely the uses that come to mind more quickly, but I generally believe our users are pretty creative, and regularly come up with ways to use jrnl that surprise me.

One quick idea that came to me yesterday was having a project journal in each git repo on my system. I could make an alias that something like `some_jrnl_alias='jrnl --config-override journals.project_todo.journal "$(git rev-parse --show-toplevel)/todo.txt" project_todo'` and then I can call `some_jrnl_alias` and get the right file no matter where I am on my system.

I strongly believe our users will come up with other, weird new ways to use this feature if we let them. So I don't want to pigeonhole this feature into being expected to be script-only.

**Comment by sriniv27** [comment]
I currently have the argument parsing implemented as a single-level JSON slug, with each key-value pair being passed in dot-notation syntax, credits to @eshrh for the idea. See test_override:test_multiple_overrides for how they will be stored after parsing, but before they are applied.

I think a "double-delimited" string could be a viable option  to bridge the gap between dot-notation and yaml/json. Consider this syntax: 
```sh 
jrnl -3 -config-override journals.scratch:"/tmp/journals/scratch.jrnl", colors.body:"green", editor: "code -w"
```
Split against `,` for key-value pairs and then against `:` for keys and values, to be passed to jrnl.overrides.apply_overrides that unpacks each key and value into the config tree. 

I think the [small] added complexity of the implementation would be worth the simplicity of the interface.

Thinking about the larger picture:
- It might be worth making `--config-override`, `--config-set`, and `--config-unset`  arguments mutually exclusive i.e. `jrnl --config-override editor:vim and --config-set journal.example:"$HOME/examples.txt`  should not be allowed even if the config targets (in the same instance) are non-conflicting. 
- the three should probably share the validator behavior as outlined in @micahellison's [comment](https://github.com/jrnl-org/jrnl/issues/1068#issuecomment-766190027) 
- I think the double-delimited syntax may be acceptable for setting and unsetting as well

**Comment by wren** [comment]
(Sorry, this got a bit long, but hopefully it clears everything up.)

@sriniv27 I really like where your PR is headed (and thank you so much for adding tests and documentation). It's looking great, but I think we need some small changes to the specific approach. The hybrid proposal (using dot notation mixed with semi-yaml/json) is going to be too difficult to maintain (see below for my qualms with this approach).

## Here's what I think should happen:
- `--config-set`/`--config-unset` should use the dot notation with spaces and only take one value at a time (although you can use it multiple times per invocation). You can use as many sets and unsets in one jrnl invocation as you want, but no other types of commands can be mixed in (not even `--config-override`).
  - Example: `jrnl --config-set journals.default.editor vim` or `jrnl --config-unset journals.default.editor` or `jrnl --config-set timeformat '%Y-%m-%d %r' --config-set highlight true` etc
  - Reasoning: These commands are for users to update their config file, and not for scripting, so one value at a time makes the most sense. If you are scripting, then it'll be easier to just edit the config file with your script directly instead of going through the jrnl cli.
  - For the multiple sets and unsets in one invocation: I'm not really set on this. I think things could get a little weird if a user tries to set/unset the same value multiple times in the same invocation (but maybe just don't do that?), but this small risk when weighed against the potential usefulness of allowing it.
- `--config-override` should also use the dot notation. This is also meant for users to interact with the jrnl config, but in a more transient way. This can be used in conjunction with normal commands, and overrides the jrnl config only for that one invocation, and is not persisted to disk.
  - Example: `jrnl --config-override editor '' --config-override linewrap 20 -n 10 -contains 'hello'`
  - Reasoning: This command is also for users to interact with their config, and this is the most clear way to do that without jumbling up which arguments are part of the config, and which are part of the journal command.;
- `--config-override-blob` (not sure about the name) is almost identical to `--config-override` but is intended for scripts (instead of user interaction). The only difference is that this command accepts a valid yaml/json blob instead. This blob should be recursively merged with the existing config (the same way we currently handle the journal-level config), and only lasts for one invocation of jrnl.
  - Example: `jrnl --config-override '{"editor": "", "linewrap": 20, "colors": {"tags": "red"}}' -n 10 -contains 'hello'` or jrnl --config-override "$(cat my_config.yaml)" -n 10 -contains 'hello' etc
  - Reasoning: By having a separate command for scripting, we can fence off this interface from the average user, and still allow scripts to be efficiently used with jrnl. By only accepting valid yaml/json, we avoid having to implement any custom parser. This greatly reduces complexity and maintenance (and bugs).


## Problems with current approach
Example: `jrnl -3 --config-override journals.scratch:"/tmp/journals/scratch.jrnl", colors.body:"green", editor: "code -w"`
- By having spaces in the args, the shell will parse them as separate arguments, and eat up the quotation marks. So, in the example, jrnl will actually receive something like this as args:
    ```
    [
      '-3',
      '--config-override',
      'journals.scratch:/tmp/journals/scratch.jrnl,',
      'colors.body:green,',
      'editor:',
      'code -w'
    ]
    ```
  - note that the quotation marks are gone
  - also note that there are trailing commas after some of the arguments (and not in between anything, only at the end)
  - This is all because the shell has already parsed the arguments before jrnl even gets to see them
  - Since there are a variable amount of args following `--config-override`, we can't know when the actual command starts (the `-3` part). This means that this flag could only be used at the end of commands, and we don't have any other flag that behaves this way. I think this would confuse users that try to use the override before the rest of the command.
- The above can all be fixed if we put the entire arg in quotes (example: `jrnl -3 --config-override 'journals.scratch:"/tmp/journals/scratch.jrnl", colors.body:"green", editor: "code -w"'`)
  - Note the single quotes around the entire override string
  - But this introduced new problems
  - The args received by jrnl will now look something like this:
    ```
    [
      '-3',
      '--config-override',
      'journals.scratch:"/tmp/journals/scratch.jrnl", colors.body:"green", editor: "code -w"'
    ]
    ```
  - Now it's up to us to parse the whole string for arguments (instead of relying on the shell, or our arg parsing library). This custom implementation would be more work, and be harder to maintain.
  - This input is sort of close to looking like a csv, so we might be able to use a library for part of the work, but not all of it. So, at least one new library will be added to the codebase, and it still won't give us reliable input.
  - Also, colons and commas and quotes are all valid characters inside of filename. This would further complicate our custom parser.
  - The editor field is a shell command itself, which means it can also contain all sorts of syntax (including nested jrnl command with their own config overrides) that would get in the way of parsing this out

There are more problems, but I don't want to beat a dead horse here. I am adamantly against this approach (and any non-standard approach).

## Options
The only viable options in my eyes are the ones that use standard parsers. Which, for this means:
1. dot notation separated by shell-standard whitespace, and optionally surrounded by quotation marks (we might have to make a small dot notation parser for this, but yaml keys from our own config have a known, limited character set controlled by us, so it's much simpler than handling user input like filenames)
2. yaml/json. we already use this in our config file, so it makes sense for this. We already use a standard library for parsing this, so it's no extra effort to parse a bit more yaml/json
3. Technically, we could use another standard language (like toml or whatever). I lean away from this since we already use yaml/json, but I'm open to talks about supporting another language if someone can make a case for it (as long as it's in common usage, and has a maintained python library to parse it)

**Comment by sriniv27** [comment]
Thank you for the detailed write-up!
I share your concerns about the maintenance of the hybrid slugs and I have reworked the arg parsing as follows: 
- Allow exactly 2 strings after each `--config-override` flag. These are collected and parsed by a custom action that also takes the liberty of converting "23","true","false" to the datatypes they represent i.e int,bool,bool respectively. 
  - This allows for multiple invocations of --config-override calls
- The actual unpacking of the overrides into the configuration still happens at runtime, after the base config has been loaded. I decided to keep it this way so as to not call any `config` module code earlier in the stack while arguments are still being parsed. 
- It seems that configuration validation would need to happen sometime between argument parsing and `run` since configuration setting/unsetting would seem to be a separate "mode" apart from running `jrnl`. 

I think `jrnl` should handle only `config-set` or `config-unset` or `config-overrides` in one call i.e. make these part of a mutually exclusive argument group. 
- I think it will be an easier maintenance and usability policy to only allow the addition/modification OR deletion of a configuration value in any one CLI invocation 
- The added user cost of one call for `config-set` and another call for `config-unset` is worth keeping the operations atomic. 

I am not sure about the concept of `config-override-blob`. Wouldn't this be functionally identical to copying an existing config, modifying it, and passing that configuration to the `jrnl` invocation via `--config-file` as proposed in #1170?

**Comment by wren** [comment]
Happy to help!

The difference for me with `--config-override-blob` and `--config-file` is that override would merge in after loading the normal config file, so it would allow you to only override some values and use the rest of your normal config. `--config-file` would use the given file and nothing else. I think that's useful for users, but maybe not? What do you think?

For the one config per call: I'm fine with that. I do think it could be useful to allow more, but I'm not really set on it, and acknowledge it might not be worth the extra effort . I think one per invocation is fine.

**Comment by sriniv27** [comment]
As I'm polishing up the PR, there's a workflow related topic I'd like to clarify: 

If I want to override journal specific config values, one option is to do so as   
`jrnl work --config-override colors.title green --config-override editor 'code -nw' ...` Let's call this **dot-anything** .

I see nothing wrong with also doing: 
`jrnl --config-override journals.work.colors.title green --config-override journals.work.editor 'code -nw' ...` Let's call this the **existing-config**

|       dot-anything            |      existing-config         | 
|-------------------------------|-------------------------------|
|   - multiple scopes in one call   |   - lower implementation complexity   |
|   - harder to implement       |       - only any one scope can be modifiable at any one time | 


**What are your thoughts?**

**Comment by micahellison** [comment]
Hi @sriniv27, are you thinking of only supporting one of these approaches, or supporting both? I would think the "dot-anything" would have to be supported, since this is a very common convention in jrnl, but I think it's fine to support the "existing-config" approach too.

Either way, jrnl is really only scoped to a single journal at runtime, since each jrnl operation only happens on one journal at once, whether it's viewing, searching, or editing. So it's not quite the case that the "dot-anything" approach has multiple scopes, once the application-level config and journal-level configs have been merged for the runtime call.
