### ISSUE TITLE
Stdin prompt doesn't show "how to close" message on some Windows systems

### ISSUE THREAD

**Issue by PrecisionWordcraft** [jrnl-org/jrnl#1178]
### Affected Page(s)

https://jrnl.sh/en/stable/usage/

### What Could Be Better?

Tell users how to end or close a new entry. 

Somehow I figured out how to do this on Linux, perhaps from jrnl --help (I don't remember). Now that I have Windows, Ctrl + D does NOT work as it does on Linux ... neither does any other character combo I tried.

**Comment by wren** [comment]
Hi! Thanks for filing an issue, and I'm sorry you're having troubles with jrnl.

> Somehow I figured out how to do this on Linux, perhaps from jrnl --help (I don't remember).

The info about which keys to press to exit the built-in writing prompt should be the first thing a user sees when that prompt comes up (I'm guessing that's where you saw it, since it's not on the help page). The reason we do it this way, is because the particular keys are dependent on the platform the user is on. For this kind of information, we opt to present that information to the user as they need it, rather than putting all possible combinations into the docs.

> Now that I have Windows, Ctrl + D does NOT work as it does on Linux ... neither does any other character combo I tried.

`ctrl` + `z` should work in a normally functioning Windows shell (and you should have been shown this information along with the writing prompt), so this sounds to me like something might be up with your particular setup (or possibly a bug in jrnl). If you can provide some info about your Windows setup, we might be able to help troubleshoot.
