### ISSUE TITLE
Unlocking jrnl with TouchID

### ISSUE THREAD

**Issue by bipvanwinkle** [jrnl-org/jrnl#1217]
### Environment

  - Jrnl `--diagnostic` output: 
  - Install method: 
  - jrnl: v2.7.1
Python: 3.9.2 (default, Feb 24 2021, 05:06:40) 
[Clang 12.0.0 (clang-1200.0.32.29)]
OS: Darwin 20.3.0

### What are you trying to do?

I am using an encrypted journal and I would like to use TouchID to unlock the journal instead of typing my password. I'm not requesting that y'all add this feature as I imagine it would be a lot of work, but I'm just wondering if any of y'all know how to get it working on a Mac.

### What have you tried?

I tried searching for a solution online, but couldn't find anything useful.

**Comment by wren** [comment]
Hi! Thank you for the question.

There's currently no way that I know of to use TouchID to unlock jrnl, although maybe one exists. We use the system keyring (Keychain) to store and retrieve passwords for jrnl. So, if there's a a way to lock Keychain with TouchID, then maybe that would do what you want?

There's a related [backend for the keyring library we use](https://pypi.org/project/keyrings.osx-keychain-keys/) that talks about a touch interface, but it says that code signing would be required, which as you say would be quite a bit of work.

If you get a chance, please report back if you find a way to enable TouchID with Keychain, and we can add that to our documentation.

**Comment by wren** [comment]
So, I've been thinking about this one and here's what I've come up with.

If we need to code sign, it would add a lot of work to the maintenance of jrnl, which is something I'd like to avoid. So, that leaves us with our only option of finding a third party app that has touch id support. I'm not sure exactly what this would look like, but maybe some keyrings have that functionality available?

Because there's no clear way forward with this, I'm unfortunately going to put this issue into "Unplanned" for now. But maybe there's another way to do this, so if anyone knows of a way (or wants to look into it more), please post info here and we'll re-prioritize as needed.
