### ISSUE TITLE
CryptographyDeprecationWarning received on encrypt/decrypt 

### ISSUE THREAD

**Issue by hrafnthor** [jrnl-org/jrnl#1245]
## Support Request
Hi,

I just updated my jrnl client from 2.4.5 to 2.8.1 through pipx, and now receive the two following warnings each time I do an `encrypt`/`decrypt` on a file:
```
/home/hrafn/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
```
  
```
/home/hrafn/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
```

As these are just deprecation warnings, the operations are ofcourse successful so there is no issue with the outputs from these operations. 

I would like to ask though if there is any component that I need to update to make this remedy this or if this is something internal within jrnl? 

##### Jrnl `--diagnostic` output: 
- jrnl: v2.8.1
- Python: 3.8.5 (default, Jan 27 2021, 15:41:15)  
- [GCC 9.3.0]
- OS: Linux 5.4.0-72-generic

##### Install method:
-  pipx

### What are you trying to do?

Doing a 'jrnl --encrypt' and 'jrnl --decrypt' causes the warnings to show up.

**Comment by wren** [comment]
Hi! Thank you for reporting this and sorry you're seeing this warning. I'm not sure where it's coming from, though, because jrnl doesn't use the deprecated call in the warning (`int_from_bytes`).

It looks like it's coming from `secretstorage`, which is a dependency of `keyring` (but only on Linux systems). I haven't seen this warning come up yet on our automated tests, but that might not mean anything since I'm not 100% sure how to repro it.

Would you mind giving some more info about your keyring setup? What password manager do you use? Do you see this warning when you don't store the encryption password in a keyring?

**Comment by wren** [comment]
Also, I found this message in [`cryptograpy`'s source](https://github.com/pyca/cryptography/blob/main/src/cryptography/utils.py#L20): 

```python
# Several APIs were deprecated with no specific end-of-life date because of the
# ubiquity of their use. They should not be removed until we agree on when that
# cycle ends.
```

It looks like the warning in this issue is intended for cryptography 3.4 (release in Feb), but maybe some libraries have held off on removing code until more recently because of this message.

**Comment by hrafnthor** [comment]
I indeed see that `keyring` is installed along side `jrnl` through `pipx`.  On my system I am using the `gnome-keyring` daemon.

When encrypting and not storing the key to the keyring the warnings are not emitted, so that would indicate where the issue lies. Just tested installing the latest version of `keyring` (version 23.0.1) through `pipx`  but still the warning shows up. 

I guess there are simply some updates outside of the scope of `jrnl` that I either have yet to do or haven't reached me as of yet (or like you said, have yet to remove their dependency due to the ambiguity of the docs), so I see no need to spend more time on this. 

Thank you again for the consideration, and for taking such a thorough look into it this quickly!

**Comment by wren** [comment]
No worries!

Last note: it looks like `secretstorage` has already implemented a fix (https://github.com/mitya57/secretstorage/issues/29), so this should go away soon as the various projects that depend on it update.

Thanks again for reporting this!
