### ISSUE TITLE
`-from` time substraction from absolute time does not work!

### ISSUE THREAD

**Issue by lamyergeier** [jrnl-org/jrnl#1257]
### Environment
  - `jrnl --diagnostic` output: jrnl: v2.8.1
Python: 3.8.5 (default, May 27 2021, 13:30:53) 
[GCC 9.3.0]
OS: Linux 5.4.0-73-generic
  - Install method: pipx

### Current Behavior

- Not correct behavior

```bash
$ jrnl time -from '2021-07-31 12:09 -1 minute' 
2021-05-31 12:09 @Breakfast

2021-05-31 17:57 @Dinner

2021-06-01 06:18 @Breakfast

2021-06-02 03:24 @Snacks

2021-06-02 13:07 @Lunch

2021-07-01 06:18 @Breakfast

2021-07-02 03:24 @Snacks
| bana;na
| pasta

2021-07-02 13:07 @Lunch

2021-07-31 12:09 @Breakfast
| c#ake
| banana
| pasta

2021-07-31 17:57 @Dinner
| "naan
| soup
```

- Correct behavior

```
$ jrnl time -from '2021-07-31 -1 minute' 
2021-07-31 12:09 @Breakfast
| c#ake
| banana
| pasta

2021-07-31 17:57 @Dinner
| "naan
| soup
```

### Expected Behavior

```bash
$ jrnl time -from '2021-07-31 12:09 -1 minute' 
2021-07-31 12:09 @Breakfast
| c#ake
| banana
| pasta

2021-07-31 17:57 @Dinner
| "naan
| soup
```

**Comment by wren** [comment]
Hello, and thank you for reporting this issue. I'm not clear on what you're saying here. Can you please elaborate?

Some questions:
- Where did you see information that would lead you to expect this behavior?
- Are you running this command on the day you are querying (`2021-07-31`)?
- Or are you trying to query a day in the past?
- If so, what would you expect `-1 minute` to do in a past date?
- Have you tried `jrnl -from '1 minute ago'`?
- Have you tried `jrnl -from '2021-07-31 12:08'`?
- Do either of those do what you're trying to accomplish?

**Comment by lamyergeier** [comment]
> Where did you see information that would lead you to expect this behavior?

I tested the following filters and they work as expected (explanation is following hash)

```
  -from '12 hr ago + 24 hr ago'                     # from 36 hrs ago
  -from '12 hr ago - 24 hr'                         # from 36 hrs ago
  -from '48 hr ago + 12 hr'                         # from 36 hrs ago
  -from '30 minute ago -40 minute'                  # from 70 minutes ago
  -from '90 minute ago +20 minute'                  # from 70 minutes ago
  -from '-90 minute +20 minute'                     # from 70 minutes ago
  -from '-70 minute'                                # from 70 minutes ago
  -from '30 minutes ago -40 minutes' -to '1 hr ago' # between 70 minutes ago and 1 hr
```

---

I was hoping that `-from '2021-07-31 12:09 -1 minute'` would show me entries from 
2021-07-31 12:08.

> If so, what would you expect -1 minute to do in a past date?

From my above tested I expected -1 minute to print the data from 1 minute before the time stamp (which is by default **now**).

> Have you tried jrnl -from '1 minute ago'?
> Have you tried jrnl -from '2021-07-31 12:08'?
> Do either of those do what you're trying to accomplish?

Yes, these I had tried and they work. But my motivation to do this was to programmatically solve  [Output after composition can be more useful and user friendly · Issue #1253 · jrnl-org/jrnl](https://github.com/jrnl-org/jrnl/issues/1253).

```bash
ErrorP="$(mktemp)"
JournalCode='time'
jrnl "${JournalCode}" "${@}" 2> "${ErrorP}"
if [[ $(cat "${ErrorP}") == '[Entry added to time journal]' ]]; then
	TimeCommand="$(echo "${@}" | sed -r -e 's/(.*):.*/\1/')"
	Time="${TimeCommand:-now}"
	jrnl "${JournalCode}" -from "${Time} -1 minute" -to "${Time}"
fi
```
If the above is inside a script then, when we try to append any entry at a specific time, then the above snippet prints all entry in the journal from 1 minute before that specific time to that specific time.

**Comment by wren** [comment]
@anishmittal2020 So, for the general approach here, jrnl can deal with with a scripted approach, and it can deal well with a more human approach, but I'm afraid it doesn't do well when you try to mix the two. If you're scripting something, it's best to get the timestamp you want, and then send that to jrnl. But scripting something to generate a more natural language query doesn't seem like it'll work out very well. I recommend taking a look at `date` in your command line (or [gnu date](https://www.gnu.org/software/coreutils/manual/coreutils.html#Date-input-formats)) to parse your timestamp before sending it to jrnl.

Another approach could be to talk to the library that jrnl uses to see if they can support what you're trying to do. I think the problem is that the query that doesn't work is mixing two types of times. You'll notice that all of your examples of times that work are relative ("n hours ago ", etc). Then there are the more timestamp sort of time ("2021-07-30 12:09"). I think mixing a timestamp with a relative date doesn't really work very well. The library that we use to parse human-readable dates is [parsedatetime](https://pypi.org/project/parsedatetime/). I don't know what they can do to help, but I'm afraid there's not much we can do on our end.
