### ISSUE TITLE
Exporting Entries with Long First Lines Results in "File name too long" Error

### ISSUE THREAD

**Issue by thw26** [jrnl-org/jrnl#1272]
### Environment

```
jrnl: v2.7
Python: 3.9.5 (default, May 24 2021, 12:50:35) 
[GCC 11.1.0]
OS: Linux 5.10.42-1-MANJARO
```

Installed via pipx on Manjaro

### Current Behavior
I am attempting to export an old journal to individual file names, but the first lines in some of these are very long. Running an export with ```jrnl $JOURNAL_FILE --format markdown --file $EXPORT/``` results in the following:

```
[ERROR: $EXPORT/$DATE_$THISFILENAMEISTOOLONG.md File name too long]
```

### Expected Behavior
jrnl should have a limit on exports for when it hits the maximum file name characters so that the export may proceed. The file name should be capped at the maximum characters.

Ideally, in the rare event that an entry is found that already exists due to this capping, having the same name, it should:

* create a new file with a number string appended, rather than overwriting the other file, to maintain both files,
* or prompt the user to review which file to keep or offer to keep both, with a number string appended.

### Repro Steps
* Create a journal entry with a long first line.
* Attempt to export it.

**Comment by micahellison** [comment]
Thanks for the filing this bug and providing all this information.

I think the best way to deal with this (if anyone is interested in resolving this before we get to it!) would be to catch this "File name too long exception" on each entry, then try again while truncating to a limit, then keep trying with progressively smaller limits until the file is saved or the limit has somehow reached 1 (which I can imagine happening deep in a Windows directory structure). This would prevent us from having to hardcode a limit, or from further bloating the configuration file.

In the meantime, if a file-based export (rather than directory-based export) is sufficient, that would be another way to export a journal with long titles to markdown.
