### ISSUE TITLE
Import From Text File Being Treated as Single Entry

### ISSUE THREAD

**Issue by viegasfh** [jrnl-org/jrnl#1330]
### Environment
```
jrnl: v2.8.2
Python: 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0]
OS: Linux 4.4.0-19041-Microsoft
```
This has been upgraded from v2.8.1 using pip.

### Current Behavior

When trying to import from a text file with the **jrnl** *txt format*, **jrnl** is adding the current timestamp to the first entry. It is treating the whole text file as a single entry and adds the timestamp at the beginning of the file.

### Expected Behavior

Importing from a text file that has several entries from a previous exported journal, **jrnl** should import them as multiple entries and not a single entry. This means, it shouldn't add the current timestamp at the beginning. It should only add a timestamp if the entry from the text file is not in the *jrnl format*.

### Repro Steps

1. First export the entries to a text file with "jnrl test --format txt --file test.txt"

In my case, I have the following content:
```
2019-09-02 09:00 Kids
Took the kids to school this morning and the younger wasn't feeling well.

2019-09-14 09:00 Heating System
Installed new heating system.
Had lunch with @Andrew.

Did some writing, but was feeling a bit blocked.
Tried to do some brainstorming, but didn't work.

2019-09-15 23:30 Just go the flu
Woke up with my nose blocked. Feeling really awful.
```

2. Import the text file to the destination journal "jrnl test2 < test.txt"

The result will be the following:

```
[2021-08-26 12:33] 2019-09-02 09:00 Kids
Took the kids to school this morning and the younger wasn't feeling well.

2019-09-14 09:00 Heating System
Installed new heating system.
Had lunch with @Andrew.

Did some writing, but was feeling a bit blocked.
Tried to do some brainstorming, but didn't work.

2019-09-15 23:30 Just go the flu
Woke up with my nose blocked. Feeling really awful.
```

The first entry gets the current timestamp and its timestamp is added to the title. This is not how we would expect.

### Other Information

If we are working with a directory based journal, the import stores the whole text in a single file with the current timestamp, treating it as a single entry instead of splitting it into a file per entry, as it should in a directory based journal. Querying it afterwards brings the entries, but they are not stored individually in its own file. That is, it works similar to the single file journal. Imports the whole text as a single entry and creates a file with the current timestamp.

So, this issue needs to be fixed for both single file journals, directory based journals, and I believe DayOne journals.

**Comment by viegasfh** [comment]
I have tried the same with the *text* format (with square brackets around the timestamp), and the result is the same. However, there is another issue I have just found. That is, if we import the text file to a new journal and then try to edit it to fix the timestamp or anything else, when saving it wipes out all the other entries, leaving only the first entry.

That is, just repeat the steps outlined above with a brand new journal. Import the text file and then do something like jrnl test -1 --edit, and fix the timestamp. When saving, it will wipe out all the other entries. However, if you add another entry after the import, this will not happen.

**Comment by micahellison** [comment]
Hi there, thanks for reporting all this. There a couple things to unpack here, but the main thing is: if you want to import data as jrnl entries, it's best to use the `--import` argument. When you pipe in text without it, jrnl interprets that text as a new entry (hence the bonus timestamp at the top of your journal). I see the documentation, while not incorrect, kind of elides this. I think that when someone (probably me!) gets around to working on #1300 that will be a bit more clear.

I also want to address with the repro steps, because it's working a little different for me:
```
>jrnl test -999
2021-02-27 10:40 test

2021-07-31 15:21 "hi"


>jrnl test --format txt --file test.txt
[Journal exported to test.txt]

>type test.txt
[2021-02-27 10:40] test

[2021-07-31 15:21] "hi"
```
I see here the "txt" format is actually working with the square brackets. I noticed a typo in your repro steps and I'm wondering if there was an error in your process. Could you try again with these steps to confirm?

And I was mentioning, for that last step, instead of doing this:
```
>jrnl test2 < test.txt
[Entry added to test2 journal]
```
You should have better luck with:
```
>jrnl test2 --import --file test.txt
[2 imported to test2 journal]
```
And to your last comment, we do have a bug file for that in #1051. Basically, jrnl needs data to start with a timestamp, and it gets quite confused otherwise. The fix we have planned is still a bit clunky, though: it would assign today's date to that chunk of data, and warn you about what happened.

**Comment by micahellison** [comment]
I'm closing this issue because the actions we'll take on it are filed elsewhere, but feel free to comment back if you have any questions or want any clarification.

**Comment by viegasfh** [comment]
Hi @micahellison ! Thanks for your reply!

I have tried the what you proposed and it is indeed working. I don't know how I was getting the date without the brackets. Maybe it was in the previous version before I upgraded to the latest version.

I had actually tried the --import before, so I think I mixed it up somehow with the file redirection.

So, it is all sorted.

Thanks once again and I guess you can close it again after my comment.
