### ISSUE TITLE
Searching Multiple Journal Files

### ISSUE THREAD

**Issue by kdhingra307** [jrnl-org/jrnl#1363]
## Support Request
Hello, thank you for creating such useful application, I was trying to search for specific tag on multiple journal files but was not able to. Even after searching through the documentation and issues, I could not find anything which can help me with that. I would also be open to contribute if this feature has not been implemented yet.

### Environment

  - Jrnl `--diagnostic` output
      - jrnl: v2.8
        Python: 3.9.6 (default, Sep 25 2021, 21:33:01) 
        [Clang 11.1.0 ]
        OS: Darwin 20.6.0
  - Install method: 
      - nix-pkg (pip) 

### What are you trying to do?
I am looking to see if we can search multiple journal files (like club their results when searching?). This might be useful when searching for tags like (remind) to look for all reminders on work, personal... etc

### What have you tried?
I have briefly looked at the documentation and search through possible issues, but could not find anything useful

**Comment by micahellison** [comment]
Hi there @kdhingra307, thanks for filing this. Unfortunately, no it's not possible, currently.

A long time ago, someone filed an issue for this in #340 and it has turned out to be a bit more complicated than it originally seemed. I'll document some of the complications in it, though you are still welcome to contribute if you are willing to take them on.
