### ISSUE TITLE
Certs broken on website

### ISSUE THREAD

**Issue by jgarte** [jrnl-org/jrnl#1408]
Your connection is not private
Attackers might be trying to steal your information from jrnl.sh (for example, passwords, messages, or credit cards). [Learn more](chrome-error://chromewebdata/#)
NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by wren** [comment]
Looked into this and updated a bunch of settings. I think it should be good now, but we have to wait for DNS to propagate, so it could be up to 72 hours for everyone to see the fixes.

Thank you for reporting this!

**Comment by wren** [comment]
After flushing the caches of the major DNS providers (Cloudflare and Google), it seems like we won't have to wait 72 hours. The site should be back up for everyone.

Also, as part of the fix for this, we moved DNS to Cloudflare, so we'll get some DDOS protection and other goodies as a result. 

Thanks again, @jgarte, for reporting this!
