### ISSUE TITLE
Cannot use neovide as the editor.

### ISSUE THREAD

**Issue by rikiwarren** [jrnl-org/jrnl#1451]
### Environment
jrnl: v2.8.4
Python: 3.10.2 (main, Feb  2 2022, 05:51:25) [Clang 13.0.0 (clang-1300.0.29.3)]
OS: Darwin 21.4.0

  - Install method: Installed through Homebrew
  
### Current Behavior
I've tried to set neovide as the editor. However, when I try to edit existing documents (.e.g. `jrnl home --edit``) it gives me an empty file. 

### Expected Behavior
It should open and edit the requested jrnl information.

I've tried setting the editor to both nvim and bbedit, and they both work.

**Comment by micahellison** [comment]
Hi @rikiwarren, I'm not sure what's going on, but I do have a few questions that might help troubleshoot:

Could you share the command line arguments you use for neovide in the "editor" key of your config? I think it's most likely related to that, due to one of these two issues:

* jrnl passes a temporary file's path as the final argument after the command you specify in your config, so it's possible that something is "eating" that path somehow.

* It may also be the case that neovide isn't acting as a blocking process. If neovide returns control to jrnl before you make your edits, jrnl can't read them. I'd expect to see the symptoms you mention if neovide is returning control to jrnl before it even opens the file -- you can tell if this is the case if jrnl is done running before you even start editing. To fix it, you'll need to add some sort of command line flag (which admittedly, I can't find in neovide's docs) to tell it to wait before returning. Maybe `-f`? That's what MacVim requires, according to [our external editors docs](https://jrnl.sh/en/stable/external-editors/).

If it's neither of the above, could you try running `jrnl home --edit --debug` and share the output? (if there is anything sensitive in it, you might want to redact). That might help if neither of the above are the issue.

**Comment by rikiwarren** [comment]
Ah, it's because by default neovide returns control to the terminal. I changed it to `neovide --nofork --multigrid` and it works beautifully. 

Thank you so much for your help!

**Comment by micahellison** [comment]
Glad to help! Thanks for reporting back with the arguments that worked.
