### ISSUE TITLE
Journal not saved if another instance of gedit is open

### ISSUE THREAD

**Issue by zachary-foster** [jrnl-org/jrnl#1483]
Thanks for elegant note taking solution! I have been enjoying it so far, but I ran in to a problem:

### Environment

```
jrnl: v2.8.4
Python: 3.10.4 (main, Mar 23 2022, 20:25:24) [GCC 5.4.0 20160609]
OS: Linux 5.17.5-76051705-generic
```
Installed with brew

### Current Behavior

I am using gedit as my editor.
When I already have a window open and I run `jrnl`, gedit opens a new tab and `jrnl` prints:

[Nothing saved to file]

and ends with the tab still open. The contents of the tab are not saved in the journal.
Adding  `--new-window` to the YAML config file, so that gedit opens in a new window instead of a tab does not help. 

### Expected Behavior

It seems it should work even when another instance of the editor program is running. 

### Repro Steps

Set editor to gedit. Open gedit. Run `jurl`.

**Comment by micahellison** [comment]
Hi there @zachary-foster, it looks like the problem is that gedit isn't acting as a blocking process -- it's basically handing control back to jrnl immediately instead of waiting until you've finished editing. Then jrnl sees no changes and lets you know that nothing was saved to the file.

Maybe it only does this when it's already been opened, but there should be a way to get it to behave consistently.

I see in gedit's source that's there is a `--wait` option for gedit that should do that, so changing your editor to the following should fix this issue:
```
editor: gedit --wait
```

**Comment by zachary-foster** [comment]
That works, thanks!
