### ISSUE TITLE
'utf-8' codec can't decode byte 0xae in position 225: invalid start byte

### ISSUE THREAD

**Issue by Ajay-056** [jrnl-org/jrnl#1623]
### Diagnostic output

jrnl: v3.2
Python: 3.10.7 (main, Sep  6 2022, 21:22:27) [GCC 12.2.0]
OS: Linux 5.15.74-3-MANJARO

### Current Behavior

Changed the default path while started first. Can't able to add any notes stuck with this error

### Expected Behavior

My note to be added in jornal.txt

### Repro Steps

Not sure

### Debug output

UnicodeDecodeError

**Comment by micahellison** [comment]
Hi @Ajay-056, thanks for the filing this. I suspect the issue is that you may have made an initial entry with a character that Python can't converted to UTF-8, probably because it is in a different character set, though I'm not sure. We know that some types of data can cause this but we haven't been able to reproduce it consistently.

Is there anything in your default journal at the path you see when you run `jrnl --list` and if so, would you be comfortable sharing it here? 

Also, could you let us know if you were using an external editor or the built-in editor?

**Comment by Ajay-056** [comment]
Here is the output of the jrnl --list

Journals defined in config (/home/******/.config/jrnl/jrnl.yaml)
 * default -> /home/******
 
 Its the built in editor BTW

**Comment by micahellison** [comment]
Thanks @Ajay-056 for the information. If there is nothing private in your default journal file, would you be willing to attach it or send it to us?

And also, if you are willing to share the output of your `locale` Linux command, that may help us troubleshoot.

And lastly, you may be able to get past this error by deleting your default journal file and starting again, though I am worried the issue may appear again until we can fix the root cause.

**Comment by Ajay-056** [comment]
Closing this issue as it was a mistake while changing the path. Missed the text file name as I thought it would create by default.
