### ISSUE TITLE
syntax error when uses parentheses in bash jrnl calls

### ISSUE THREAD

**Issue by eleehiga** [jrnl-org/jrnl#1699]
### Diagnostic output

```
jrnl: v3.3
Python: 3.11.2 (main, Feb  7 2023, 13:52:42) [GCC 11.3.0]
OS: Linux 5.19.0-31-generic
```

### Current Behavior

Running a jrnl entry with a paranthesis such as `jrnl today: y (e) s` leads to the following error `bash: syntax error near unexpected token '('` Also running a jrnl entry with only one apostrophe (I understand that two apostrophes would work without an issue) such as `jrnl today: y'es` would lead to the command line hanging at `> `. 

### Expected Behavior

I would expect this journal entry to save without any problems from both of these inputs

### Repro Steps

Run any journal entry with parenthesis and another one with only one apostrophe

### Debug output

Same `bash: syntax error` and hanging at `> ` as above

**Comment by wren** [comment]
Hi, @eleehiga! Thanks for filing this issue.

It looks like you're running into reserved characters for `bash` in your attempted entry. We mention this in the [basic usage](https://jrnl.sh/en/stable/usage/#composing-entries) section of our documentation.

Basically, since you're using a shell (`bash`) to send entries to `jrnl`, that shell processes your input first, before that input ever gets to `jrnl`. So, you can't use reserved characters for that shell (for `bash`, `(`, `)`, single and double quotes, and `>` are all reserved characters).

A quick and easy way around having to worry about reserved characters is to quote all of your input. So, something like `jrnl 'y (e) s'` would tell your shell that you don't want it to process your input, and send it all to `jrnl` (and since you're using quotes like this, you would then need to escape, your apostrophe).

The other option is to use your editor to add new entries to `jrnl` (honestly, this is why the editor mode exists in `jrnl`). If you just type `jrnl` without any arguments, your editor will be opened to a new file (you can change which editor is used in your [config file](https://jrnl.sh/en/stable/reference-config-file/#editor)). Once your editor opens, you can type whatever you want (including shell reserved characters), and jrnl will process them directly without `bash` getting in the way.

Let us know if you have any questions about this.
