### ISSUE TITLE
Store Journals in folder (with multiple files)

### ISSUE THREAD

**Issue by matthiasbeyer** [jrnl-org/jrnl#170]
Hi,

I think it would be great if the program would use several files instead of just one file. One file per day would be feasable, I think!

**Comment by matthiasbeyer** [comment]
Will this be implemented? It's open for over half an year now... and it seems nothing has happened...

**Comment by notbalanced** [comment]
Hey, I've got something working on my fork of jrnl, in the "folder" branch. There are some bugs with deleting/editing entries, still, so not really ready for prime time, but if you'd like to try it out...feel free.

**Comment by flight16** [comment]
This issue is important to me, too.  I just found jrnl and it looks like everything I wanted, except the directory/file structure.  Is this still being considered by @maebert ?  Is there anything I can do to help?

**Comment by matthiasbeyer** [comment]
@flight16 :+1:

**Comment by flight16** [comment]
@notbalanced I had a look at your change, and it appears you added the changes to the base Journal class.  Just curious, what issues did you run into when editing and deleting entries?  Were these implementation bugs or design issues?

I am not the author of jrnl, but I think we could cleanly solve this issue by enhancing cli.py and the config to support arbitrary journal formats.  There is already DayOneJournal that is hard-coded.  All that needs to be done is to create a mechanism to optionally tag a journal as a specific format, and then instantiate the associated class.  So I see this issue as "Support custom journal formats".

@maebert Would you accept a pull request for the above enhancement?

**Comment by notbalanced** [comment]
@flight16 Hi, my implementation is actually a new Folder class derived from the Journal class (similarly to what is done with the DayOne class.) In the cli.py, I do instantiate the Folder class if the journal in the .jrnl_config is a folder that **doesn't** have ".dayone" in the folder name.

 It works just fine for adding entries to the journal. But when you use the --edit flag, and then delete an entry, it doesn't get deleted. (You'd have to go into the txt file and delete it manually.) I run into this problem because I can have multiple entries in one file (unlike the dayone journal that only has 1 entry per file). I haven't had time to figure out a way to identify which entry gets deleted, so that it doesn't get written when you update the file.

There is also the issue that if you only have 1 entry in a file and delete that entry, that the code doesn't delete the file.

Finally, I haven't had the time to run the tests on the update. I'm pretty sure I've broken something there, so I need to update those tests and add additional tests to cover this new journal type.

**Comment by matthiasbeyer** [comment]
Please note that I'm still interested in this.

**Comment by wren** [comment]
@notbalanced @flight16 @matthiasbeyer Thanks for your interest in the project! I just wanted you to know that this is one of my favorite features, and I plan to prioritize it.

We're just getting the project back up running right now, though, and need some time to get everything organized. Thanks for waiting, and look out for this feature!

**Comment by matthiasbeyer** [comment]
Let me note that I have implemented a diary (and a "log", as a "oneline-diary") module in [imag](https://imag-pim.org) already and it is working and I am actively using it.

I'm leaving this open anyways because others might be interested in such a functionality/feature.

**Comment by matthiasbeyer** [comment]
Can this be closed?

**Comment by wren** [comment]
Not yet! We're automating the changelog, and need this to stay open for now until we get that done.

**Comment by paanvaannd** [comment]
Hey, folks! Sorry for the thread necromancy and thank you all for the work on this.

I just started using `jrnl` and want to enable this feature but I can't seem to find documentation on how to do this. Is there something I need to add to `jrnl.yaml` for this?

After enabling this feature, will `jrnl` retroactively split my monolithic file into different entries in the above subdirectory structure or will I have to manually port those over?

**Comment by micahellison** [comment]
Hi there @paanvaannd, thanks for posting about this. We're working on a docs change to address this problem (pr #1331, preview [here](https://jrnl--1331.org.readthedocs.build/en/1331/journal-types/)), though your comment makes me realize we should have instructions on how to migrate a single file journal to a folder journal.

To start with your last question: no, jrnl won't retroactively work on your journal. You'll want to create a new journal, then move your entries to it.

To create a folder journal:
* First create the directory where your folder journal will be
* Then add a new journal to your `jrnl.yaml` with a `journal` key pointing to that path, like so:
```
  newfolderjournal:
    journal: C:\Users\micah\Documents\new-folder-journal
```

To move your old journal's entries to your folder journal: first, make sure you are running jrnl v2.8.3 or later (`jrnl --version`) because it has a bug fix regarding this. Then, run the following, replacing the names of your journals as appropriate:
```
jrnl oldjournal --format text | jrnl newfolderjournal --import
```
