### ISSUE TITLE
Support Request

### ISSUE THREAD

**Issue by porterbhall** [jrnl-org/jrnl#1784]
### Diagnostic output

jrnl: v4.0.1
Python: 3.11.4 (main, Jun 20 2023, 16:52:35) [Clang 13.0.0 (clang-1300.0.29.30)]
OS: Darwin 20.6.0

### What are you trying to do?

I'm trying to get into my encrypted journal, but it won't accept my password.

### What have you tried?

Every possible password I can think of. I was the person who reported the cryptography dependency issue with homebrew. Before I reported it, I uninstalled and reinstalled  4.0.1_3 through Homebrew to see if that would resolve the issue. Once the fix came out, I upgraded to 4.0.1_4, but couldn't get in with my password. I then uninstalled and and installed 4.0.1, but ran into the same issue. 

### Other Information

Is it possible that uninstalling 4.0.1_3 removed my hashed password? Is there any way to decrypt my journal?

**Comment by micahellison** [comment]
Hi @porterbhall, I'm not sure what's going on, but here's what I do know.

I can't think of a way that jrnl could have affected your password when it wasn't able to load the cryptography dependency. It crashed before reading the file, so it wouldn't have written anything to the file, and therefore wouldn't have affected the password.

I was worried that possibly there was something strange between the vanilla version of jrnl 4.0.1 and the latest brew version 4.0.1_4, so I did this and confirmed that it still works:
* Created an encrypted journal in Windows 10 Pro using jrnl 4.0.1 installed via pipx
* Installed WSL/Ubuntu 22.04.2 then linuxbrew, then ran it to install jrnl 4.0.4_4
* Opened the same journal in that environment successfully

However, this isn't quite the same environment as yours, and I'm not sure what else might be at play.

In most of the cases I've seen where a journal can't be decrypted, it's because of some data added to it that shouldn't be there. For instance, if you removed `encrypt: true` from the config file then wrote a journal entry, jrnl would add a plaintext entry to the end of your otherwise encrypted journal and make the whole journal impossible to decrypt without manually removing that entry. It might be worth inspecting your jrnl file with a text editor to confirm that something like this isn't happening. You'd see a big chunk of garbled data followed by readable plaintext.

Another approach you might take would be to remove jrnl then use a supported version of Python and pipx to install jrnl ([instructions](https://jrnl.sh/en/stable/installation/)). If there really is a problem with Homebrew and jrnl on macOS, this more "vanilla" installation would rule that out.

I hope this helps. Please let us know if you discover a solution or would like any more help troubleshooting. And to any macOS users that have a similar problem or any insights on what else could go wrong, feel free to add your findings here.

**Comment by porterbhall** [comment]
Thank you so much. I did try changing the config when I was troubleshooting. Looking at the file, I see a timestamp followed by a long string of chars in a single line.

[2023-08-09 12:17] gAAAAABk...

I removed the datestamp and that solved the issue! Thanks again.

**Comment by micahellison** [comment]
Awesome, you're very welcome! I'm glad to hear that worked.
