### ISSUE TITLE
Support Request: Does config file support YAML anchor/alias?

### ISSUE THREAD

**Issue by alpineyahoo** [jrnl-org/jrnl#1786]
### Diagnostic output

```
$ jrnl --diagnostic
jrnl: v4.0.1
Python: 3.11.5 (main, Aug 24 2023, 15:18:16) [Clang 14.0.3 (clang-1403.0.22.14.1)]
OS: Darwin 23.0.0
```

### What are you trying to do?

I'd like to rewrite jrnl config file using YAML anchor/alias. I did as a test like this:
`~/.config/jrnl/jrnl.yaml`
```
var: &dir ~/.local/share/jrnl
journals:
  default: *dir/journal.txt
```
This didn't work(; this behaviour is what I expected, though.)

### What have you tried?

Maybe the asterisk is the problem; jrnl doesn't expect an asterisk symbol in "journals" path-setting line in config file.
I don't know much about YAML spec. Can anchors/aliases in YAML include a slash(/) symbol anyway?

### Other Information

Is there any way to write config file simple? I would like to avoid seeing the long path names in config file many times.

**Comment by micahellison** [comment]
Hi @alpineyahoo, jrnl's config file does support YAML anchors and aliases, but unfortunately YAML doesn't support concatenation of aliases and other data.

The only way I can think of to keep from repeating these paths in your config file would be to use an environment variable then reference it with `$`. For instance, if you set the MY_PATH environment var in your OS to `~/.local/share/jrnl` then you should be able to use this for your default journal's path: `$MY_PATH/journal.txt`

The downside, however, is that if MY_PATH is ever not set, then jrnl will look for your journal in a folder in the current directory called $MY_PATH and it will create it if not found. It will notify you that it has created a new journal, however, so that would be your sign to fix the environment variable.

I don't think this is ideal--I'd rather do a little copy-pasting than have a dependency on an environment variable I may forget to set again if/when I migrate my files to a new system--but it's the only solution I can think of.

**Comment by alpineyahoo** [comment]
Thanks, @micahellison. I'll close this issue.
