### ISSUE TITLE
Encrypted Journal on different Cpmputers

### ISSUE THREAD

**Issue by AlFranz1** [jrnl-org/jrnl#1808]
### Diagnostic output

Nothing :)

### What are you trying to do?

On Machine A (fedora Linux) I write into a journal, named "secret".
On Machine A, i encrypt the secret journal with password 123 (simple, only for testing)
Then, this is synced to nectxloud with the Nextcloud Sync Manager.

On Machine B, secret.txt is synced via Nextcloud sync.
On Machine B (OSX), i try to decrypt the secret  with the password 123.

Errormessage: **Wrong Password**

The other way around as well.

### What have you tried?

See above.

### Other Information

Is this possible at all? (no problem with decrypted journals)
I want to use encrypted journals on multiple machines.

**Comment by micahellison** [comment]
Hi @AlFranz1, this is possible, though I think something may have happened to your journal's data to prevent it from being decrypted.

In most of the cases I've seen where a journal can't be decrypted, it's because of some data added to it that shouldn't be there.  For instance, if you used your second computer to add an entry to the encrypted journal before adding the `encrypt: true` config key, it would add plaintext to the end of the file but make it impossible for jrnl to decrypt the file. It might be worth inspecting your journal file with a text editor to confirm that something like this isn't happening. You'd see a big chunk of garbled data followed by readable plaintext. [We saw someone else with this issue a while back and they were able to fix it by removing the plaintext](https://github.com/jrnl-org/jrnl/issues/1784#issuecomment-1675129419).

Also, if you aren't using the latest version of jrnl (4.0.1; run `jrnl --version` to confirm), you might be running into an older problem that has since been resolved: if you create an empty journal and encrypt it, it can never be decrypted. Upgrading to the latest version should fix this.

Lastly--this is a long shot--I don't know if NextCloud mangles txt files with binary data in them, but that's not unheard of with other file transfer tools. They try to get clever when they see something looks like line endings or certain types of encoded text. So I wonder if changing the file extension might help. I like to use ".jrnl" or ".enc" for encrypted journals.

I hope that helps! Please let me know if it does, or if you want any more help troubleshooting.

**Comment by AlFranz1** [comment]
This seems to work, thank you very much.
However, I changed two things at the same time:
1. used the .enc file extension
2. used a less complicated password with fewer special characters.

As soon as I have more time again, I can find out more precisely which of the two finally helped.

**Comment by micahellison** [comment]
You're very welcome! I'm glad that helped.

I'm closing this issue, but feel free to comment back here if you've got more info on what worked for you.
