### ISSUE TITLE
Crash in v4.0.1_5 (Homebrew)

### ISSUE THREAD

**Issue by dirtyhabits97** [jrnl-org/jrnl#1823]
### Diagnostic output

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/jrnl", line 5, in <module>
    from jrnl.main import run
  File "/opt/homebrew/Cellar/jrnl/4.0.1_5/libexec/lib/python3.12/site-packages/jrnl/main.py", line 8, in <module>
    from rich.logging import RichHandler
  File "/opt/homebrew/Cellar/jrnl/4.0.1_5/libexec/lib/python3.12/site-packages/rich/logging.py", line 15, in <module>
    from .traceback import Traceback
  File "/opt/homebrew/Cellar/jrnl/4.0.1_5/libexec/lib/python3.12/site-packages/rich/traceback.py", line 23, in <module>
    from pygments.lexers import guess_lexer_for_filename
ModuleNotFoundError: No module named 'pygments'
```

### Current Behavior

When installing `jrnl` via `homebrew`, it crashes.

It seems like `pygments` can't be found even though I see it specified in [the homebrew formula](https://github.com/Homebrew/homebrew-core/blob/40df08ee10198cc414267a276636f5c9cdc63113/Formula/j/jrnl.rb#L23)

### Expected Behavior

`jrnl` shouldn't crash

### Repro Steps

```
brew install jrnl
jrnl -- version
```
Results in a crash

### Debug output

No useful output, is just an instant crash:
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/jrnl", line 5, in <module>
    from jrnl.main import run
  File "/opt/homebrew/Cellar/jrnl/4.0.1_5/libexec/lib/python3.12/site-packages/jrnl/main.py", line 8, in <module>
    from rich.logging import RichHandler
  File "/opt/homebrew/Cellar/jrnl/4.0.1_5/libexec/lib/python3.12/site-packages/rich/logging.py", line 15, in <module>
    from .traceback import Traceback
  File "/opt/homebrew/Cellar/jrnl/4.0.1_5/libexec/lib/python3.12/site-packages/rich/traceback.py", line 23, in <module>
    from pygments.lexers import guess_lexer_for_filename
ModuleNotFoundError: No module named 'pygments'
```

### Other Information

Just in case, this is my config file:
```
colors:
  body: none
  date: yellow
  tags: magenta
  title: none
default_hour: 9
default_minute: 0
editor: nvim
encrypt: false
highlight: true
indent_character: '|'
journals:
  default:
    encrypt: false
    journal: $HOME/.local/share/jrnl/journal.txt
linewrap: 79
tagsymbols: '#@'
template: false
timeformat: '%Y-%m-%d %H:%M'
version: v4.0.1
```

**Comment by micahellison** [comment]
Hi there, sorry to give you the runaround, but you'll have better luck reporting this in the [Homebrew core community](https://github.com/Homebrew/homebrew-core/), since this problem resulted from a change to how Homebrew is packaging jrnl (our last release was v4.0.1 and we don't put out releases with underscores). Providing them with the diagnostic info they request in their issue template might help them resolve the problem. If you do this, feel free to link back here in case anyone else is running into this problem.

Alternatively, we're about to release v4.1 in the next few days if there aren't any major issues with the beta (so far, so good). That will trigger a pull request to change the formula with their bump-formula-pr tool, and that might alleviate this problem with the new dependencies that it specifies.

Or, if you'd like to be sure that you're using the same dependencies that we test before releasing, you can use [pipx](https://pypa.github.io/pipx/) to install jrnl.

**Comment by dirtyhabits97** [comment]
I ended up uninstalling (`brew uninstall`) and reinstalling (`brew install`) the dependencies specified in[ jrnl's formula](https://github.com/Homebrew/homebrew-core/blob/40df08ee10198cc414267a276636f5c9cdc63113/Formula/j/jrnl.rb#L23). 

Is not ideal, but the tool works as expected now!
