### ISSUE TITLE
No module named 'pygments' after pygments upgrade

### ISSUE THREAD

**Issue by porterbhall** [jrnl-org/jrnl#1887]
### Diagnostic output

My jrnl is failing since doing a package upgrade in Homebrew. My upgrade took pygments from pygments 2.17.2 to 2.18.0.

### Current Behavior

Errors out when trying to execute any jrnl command.

### Expected Behavior

Should be able to execute every jrnl command

### Repro Steps

1. Upgrade pygments to 2.18.0
2. Run jrnl

### Debug output

`Traceback (most recent call last):
  File "/opt/homebrew/bin/jrnl", line 5, in <module>
    from jrnl.main import run
  File "/opt/homebrew/Cellar/jrnl/4.1/libexec/lib/python3.12/site-packages/jrnl/main.py", line 8, in <module>
    from rich.logging import RichHandler
  File "/opt/homebrew/Cellar/jrnl/4.1/libexec/lib/python3.12/site-packages/rich/logging.py", line 15, in <module>
    from .traceback import Traceback
  File "/opt/homebrew/Cellar/jrnl/4.1/libexec/lib/python3.12/site-packages/rich/traceback.py", line 23, in <module>
    from pygments.lexers import guess_lexer_for_filename
ModuleNotFoundError: No module named 'pygments'`

### Other Information

I can probably resolve this by downgrading and pinning to the last version of pygments, but that's a bit tricky with homebrew. I'm hoping maybe there's a better way.

**Comment by micahellison** [comment]
Hi @porterbhall, this has been an ongoing issue with brew (#1823, #1827). With the next jrnl release, it will likely go away, though our release cadence is slow so it will probably return again.

The easiest workaround is to install jrnl with [pipx](https://pipx.pypa.io/stable/) instead of brew, since pipx isolates dependencies in a virtual environment, allowing you to have multiple versions of each dependency installed. We're looking at changing the recommended default installation to pipx in part for that reason (#1888).
