### ISSUE TITLE
jrnl-org/nostr?

### ISSUE THREAD

**Issue by ghost** [jrnl-org/jrnl#1905]

**Comment by micahellison** [comment]
I don't want to add any network code to jrnl for a few reasons, mainly because it's a huge maintenance burden to support the shifting landscape of protocols and security issues. We would have to release much more frequently, and we'd still likely do a worse job than any of these third-party tools. Also, I think one of the things that makes jrnl trustworthy is that it has no networking capability at all. I think any new network feature would compromise that trust.

However, if you want to do this with jrnl, the feature that would enable this would be application hooks as described in #921. You'd use whatever command line tool you use to post to nostr using data fed from a hook on a new entry. Or, for a less resilient but immediately usable solution, you can use a shell script wrapped by an alias as described in [this comment](https://github.com/jrnl-org/jrnl/issues/921#issuecomment-1793845901).
