### ISSUE TITLE
unable to install jrnl on Linux Mint 22 laptop

### ISSUE THREAD

**Issue by trebor7-1** [jrnl-org/jrnl#1916]
### Diagnostic output

pipx install jrnl
jrnl: Unknown metadata version 0.5. Perhaps it was installed with a later
version of pipx.

### What are you trying to do?

failing to install jrnl

### What have you tried?

I've installed on several other Linux Mint PC without issue. pipx version is pipx --version
1.4.3

### Other Information

pipx seems to be ok and runs the demo pycowsay mooo

**Comment by micahellison** [comment]
Hi @trebor7-1, I'm not sure what the issue is. This isn't a jrnl error and I can't find anything online about this pipx error in any context.

Some things to try:

* Confirm you don't have multiple versions of pipx on your system
* Use the latest version of pipx
* Maybe it's somehow installed already? Run `pipx uninstall jrnl` then `pipx install jrnl`
* Verify that you're using a version of Python supported jrnl (currently Python 3.10 or higher)
* Investigate the environments of your other Linux Mint PCs to see what's different

Feel free to report back if any of those approaches help. Otherwise, you might have better luck with the [pipx community](https://github.com/pypa/pipx).

**Comment by trebor7-1** [comment]
Thanks for the reply Micahellison, unfortunately pipx uninstall jrnl gave the same error message as attempting to install.
Python is 3.12.3. Any idea what I should be looking for on the working versions ?
I will give pipx a shout as well...

**Comment by trebor7-1** [comment]
Hi Micahellison, had a look here,  /home/rob/.local/share/pipx/venvs and found that the jrnl had been installed with python 3.10.x. The upgrade to Linux Mint 22 changed  python  to 3.12.3 and I guess cased the error I was seeing. Deleted the version of jrnl in that environment and re installed again with no problems. Thanks for your suggestion that let me to find that. :-)

**Comment by micahellison** [comment]
I'm glad that worked out. Thanks for reporting your findings here.
