### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by larrym** [jrnl-org/jrnl#1949]
### Diagnostic output

![image](https://github.com/user-attachments/assets/e29dfcdc-1020-42f7-9154-591234be1ed0)

### Current Behavior

Tried to print a listing. I probably did it wrong, but I followed the QuickStart guide.

### Expected Behavior

Meaningful output

### Repro Steps

jrnl -to today

### Debug output

[jrnl.err.txt](https://github.com/user-attachments/files/17580249/jrnl.err.txt)

### Other Information

Ubuntu 24.04.1 LTS
Filetype txt added to /home/larry/.config/jrnl/jrnl.yaml
[jrnl.yaml.txt](https://github.com/user-attachments/files/17580283/jrnl.yaml.txt)

**Comment by micahellison** [comment]
Hi @larrym, the issue is that your `jrnl.yaml` config file isn't valid YAML, specifically on line 8, column 10 like the error message mentions:
```
editor: 'vim -c 'set viminfo= noswapfile noundofile nobackup nowritebackup noshelltemp history=0 nomodeline secure''
```
The YAML parser can't tell what to do with these various nested single quotes. You should be able to get around the issue by removing the outer quotes like so:
```
editor: "vim -c 'set viminfo= noswapfile noundofile nobackup nowritebackup noshelltemp history=0 nomodeline secure'"
```
For any interested contributors, this is a good use case for #1682 which should hopefully make these YAML issues a little easier to understand.
