### ISSUE TITLE
Use GPG to encrypt journal

### ISSUE THREAD

**Issue by gioele** [jrnl-org/jrnl#262]
Could jrnl use GPG instead of raw AES encryption?

Using the GPG symmetric encryption mode is a better alternative to raw AES, as it is carefully tuned to avoid many classes of bugs that arise from the use of raw AES, see [If You're Typing The Letters A-E-S Into Your Code, You're Doing It Wrong](http://www.cs.berkeley.edu/~daw/teaching/cs261-f12/misc/if.html) and the comments at https://news.ycombinator.com/item?id=639647.

**Comment by jonhoo** [comment]
I'd be in favor of re-opening this. Offering the *option* to use `gpg` encryption and decryption would greatly simplify the life of users who are already using GPG. It eliminates the need to keep and type two passwords (for those users), simplifies tuning encryption preferences, and allows access to the plain text files using standard tools (instead of the [documented](https://maebert.github.io/jrnl/encryption.html#manual-decryption) but unorthodox manual decryption Python script).

**Comment by maebert** [comment]
Unfortunately, to my knowledge there is no implementation of GPG that can be installed as a dependency on Python, hence GPG would require external libraries. I'm open to this as an option if somebody wants to write the appropriate backend on the 2.0 branch

**Comment by jonhoo** [comment]
I was imagining GnuPG support to be optional, meaning that you could add an optdepends on [python-gnupg](https://pythonhosted.org/python-gnupg/), import it only if the config specified to use GPG, and fail with an error if GPG was requested but not installed?

**Comment by pv** [comment]
The "encryption" in jrnl.sh is anyway easily bruteforceable as it uses a hash function instead of a key derivation function for producing the private key from the password.

**Comment by insanerwayner** [comment]
Came to look for this feature. I think it would great to have the option to use GnuPG for us users that are already using it. It would definitely be a good way for easy decryption if someday the jrnl project were somehow lost or broken. PGP is a standard that has stood the test of time.
