### ISSUE TITLE
Plugin Framework

### ISSUE THREAD

**Issue by sagarjauhari** [jrnl-org/jrnl#282]
Are there plans to have a plugin framework  for jrnl? (something like pytest)

**Comment by flight16** [comment]
How about requiring plugins to be proper python packages in namespace jrnl.plugin.*?  It's good for us because we don't have to write and maintain code that interfaces with gists.  It's the same for the user because they can use "pip install http://github..." which appears the same as "dashing install abcdef" for all intents and purposes.  It gives the author the bonus of distributing the package in a more traditional way, too.

**Comment by flight16** [comment]
It would be cool if plugins allowed for adding custom commands and options.  As a real example, I wanted to create the following command:

> jrnl -stats --full

That would list statistics about all of my journals (entries this week, entries total, avg. entries per week, etc).  It looks like Cement can handle such a task pretty well.  http://builtoncement.com/2.4/dev/plugins.html

But I'm not sure how that would look in jrnl because the way I see it, jrnl doesn't really have any traditional, explicit commands.  It instead infers the user's intent from what combination of options the user specified.  I am wondering if, for 2.0.0, CLI redesign should be considered.  For example:

| Current      | Possible alternative |
| -------------| ---------------------|
| jrnl -ls     | jrnl ls              |
| jrnl -n 3              | jrnl read -n 3       |
| jrnl work -until today | jrnl read work --until today |
| jrnl -from yesterday | jrnl read -f yesterday |
| jrnl work "My entry" | jrnl write work "My entry" |
| jrnl --edit -from today | jrnl edit --from today |
| jrnl --export md     | jrnl export md |
| jrnl --help          | jrnl help write # detailed write-specific help |
| ?                    | jrnl import work --input=incoming.xml --format=Xml |
| ?                    | jrnl myneatplugin --sort=date |

I prefer the right-hand column as a user because it is more predictable.

For the most common operations of 'jrnl read' and 'jrnl write' two scripts could be included as wrappers:

* jrnlr -> Wrapper around 'jrnl read'
* jrnlw -> Wrapper around 'jrnl write'

So you could type things like "jrnlw 'Entry to default journal for today'".

This would also allow anybody to create a new command with additional options.

I really like the flexability of the current interface, and it's pretty cool the way it figures out what you want to do, but my opinion is that dynamicness is limiting the ability to create plugins, increasting code complexity, and has a bit of a learning curve for the user.

I just wanted to bounce the idea off you and others and see what you think of the above idea or if it's too radical of a departure for 2.0.0.

**Comment by derks** [comment]
WRT Cement, plugins can be loaded in two different ways, either from a module like `jrnl.plugins.myplugin` or from a plugin directory such as `/usr/lib/jrnl/plugins/myplugin.py`.  Therefore you could go the shared namespace route, or simply pull down the plugins and drop them in the configured `plugin_dir`.

I think for the best user experience, having something like: `jrnl plugin install myplugin` would be ideal.  This could either `pip` install from Git, or `wget` the plugin down and extract it to `/usr/lib/jrnl/plugins`.  Just a thought.

Also, happy to answer any questions regarding Cement that you might have.

**Comment by sagarjauhari** [comment]
I have really started loving the way [Vundle](https://github.com/gmarik/Vundle.vim) does things for vim - u can load plugins from local files or github or wherever.

**Comment by flight16** [comment]
I see this is in the milestone for 2.0.0.  Is there anything concrete to do to wrap up this issue and get us that much closer to 2.0.0?  If this needs a lot more thought, design, and consideration, maybe it's fit for 3.0.0 so at least 2.0.0 can get shipped with its enhancements and bug fixes?

**Comment by wren** [comment]
I think plugins sounds like a great idea. It never quite made it to the roadmap, and we're a ways away from being able to implement. I like it, though, so I'm going to put it in the ideas bucket to come back to when we're better organized.
