### ISSUE TITLE
Feature Request: Importing/Merging journals

### ISSUE THREAD

**Issue by pandemie** [jrnl-org/jrnl#395]
it would be great if something like the following would work:

```
jrnl journal_1 --export json > journal_1.json
jrnl journal_2 --import json journal_1.json
```

or 

```
jrnl journal_1 --export json | jrnl journal_2 --import
```

Which would add all entries from journal_1 to journal_2, excluding duplicates.

My use case is, that I have two machines (work & home) where I want to edit the same journal, but have no possibility access the same file system (also no Dropbox at work allowed). With such an import option I could occasionally sync the journals up using some offline/e-mail method.

**Comment by philipsd6** [comment]
I agree! I'm currently backing up my journal to .json files (because I had a nasty corruption of my journal file one time) and it would be nice to be able to import these files to recreate my journal, though I haven't had to do that yet thankfully.

In the meantime, you can create a merged json file with [jq](https://stedolan.github.io/jq/):

~~~sh
jrnl journal_1 --export json > journal_1.json  # transfer this to your #2 machine...
jq -s '{entries: (.[0].entries + .[1].entries)|unique|sort_by(.date + .time), tags: (.[0].tags * .[1].tags) }' journal_1.json =(jrnl journal_2 --export json) > merged_journal.json
# Using zsh's =() process substitution there...
~~~
But until `jrnl` can import its own export files, you'll need to reconstruct your flat file yourself:
~~~sh
jq -r '.entries[]|[.date, " ", .time, " ", .title, if .starred then " *" else "" end, "\n\n", .body|rtrimstr("\n")]|join("")' merged_journal.json > $(jq '.journals["journal_2"]' ~/.jrnl_config)
~~~
Clearly I have too much time on my hands...
:warning: Oh, and of course, back up your journal files before doing this, just in case anything goes wrong!

**Comment by wren** [comment]
This is an interesting idea. I think jrnl needs quite a bit of work before we can implement a feature like this. I'm going to put this in the ideas bucket for now, but I can definitely see coming back to this once a few of the underlying requirements for this have been implemented.

**Comment by gregorybodnar** [comment]
I'm interested in this as well as can probably contribute some effort after the release is sorted out.

I have a bunch of project journals that I use for work, so merging has come up, as well as moving entries between journals as a project gets spun up from an idea.
