### ISSUE TITLE
Pretty print journal entry titles as bold

### ISSUE THREAD

**Issue by briancecker** [jrnl-org/jrnl#508]
There is already a visual distinction created by the `|` at the beginning of the journal entry lines, but when you want to quickly skim through the entries looking at titles, it's nice to have a stronger distinction in my opinion. Making the titles bold accomplishes this nicely. I already put together the PR since it's literally just a few lines, but the contributing guidelines say to make an issue first.

**Comment by jez** [comment]
As an alternative, I've been using the [`viewjrnl` program][1] to pretty print journal entries in the terminal. In addition to adding some color to entry titles, it groups entries by date to make scanning a multiple days worth of output easier.

[1]: https://github.com/jez/viewjrnl

**Comment by wren** [comment]
Yup, this is a great idea!

Looks like there's already a submitted PR for this issue, but it has failing tests. If anyone wants to fix and resubmit.

This seems like a great first issue for anyone that wants to start contributing to this project. Otherwise, we'll get this scheduled into a later release (after the current milestones).
