### ISSUE TITLE
Poor performance when adding a new entry without arguments

### ISSUE THREAD

**Issue by sorsasampo** [jrnl-org/jrnl#529]
When running just `jrnl` without arguments for a large journal file, it takes a while until `jrnl` opens the editor.

This is probably related to `jrnl` reading all entries? And that in turn leads into issues like #502.

When running without arguments, `jrnl` should start the editor right away, and do heavy lifting after the editor has been closed.

**Comment by insanerwayner** [comment]
I've been experiencing this same thing especially now that my file has gotten to almost 5MB. I've been considering archiving the old entries into individual journal files by year, and just addressing them in my config file separately. A tad bit of inconvenience, though as it'd be nice to be able to keep it all together to do queries through all of time rather than having to go to each file separately.

**Comment by wren** [comment]
This should be fixed in v2.0. You can install the release candidate with `pip install jrnl==2.0.0rc2` if you want to try it out, or it'll be out soon.
