### ISSUE TITLE
Day names for date not treated consistently for new entry, some days get added to now.

### ISSUE THREAD

**Issue by Ragnar79** [jrnl-org/jrnl#662]
This was tested on a Wednesday.

If I add an entry for Tuesday it works as expected:
`jrnl tuesday: Test Tuesday` > `[2019-09-24 09:00] Test Tuesday`

Adding entry for Monday, Sunday, and Friday is not working as expected, it gets added to today:
`jrnl monday: Test Monday`, > `[2019-09-25 14:43] monday: Test Monday`

Adding a space after day name works as expected:
`jrnl monday : Test Monday` > `[2019-09-23 09:00] Test Monday`

**Comment by wren** [comment]
Hi, @Ragnar79. Thanks for submitting an issue!

Can you please provide some additional details?

- What version of jrnl are you using? (run `jrnl --version`)
- What operating and version system are you on? (Windows 10, Mac 10.14, etc)
- What version of Python do you have installed? (run `python version`)

This will give us some better tools to confirm your report and track down the possible bug.

Thanks!

**Comment by notbalanced** [comment]
Hi,
I'm running `jrnl --version = 2.0.0-rc3` (basically the latest master branch) on Debian Buster with Python 3.7.3.

It appears that this issue was introduced by the Pull request #623 in the time.py module.

The lines:
```
if len(date_str) <= 6:
        return None
```
will reject any date parse string like `mon` or `monday`.

I also noticed when I do a command like: `jrnl @tag -from mon` (which used to work), it now doesn't honor the date parse string (because it is <=6 chars).

**Comment by wren** [comment]
Ah, good catch! That part is there to stop markdown footnote syntax (`[1234]`) from accidentally being read as a date. It's a temporary patch, since we need to do a few fixes on the date parsing in general.

We should change the above line to `if len(date_str) < 5` to account ride the line between the markdown syntax, and the more casual datestamps. That means `mon` still won't work, but `monday`, `today`, etc will work again (hopefully nobody has more than 9999 footnotes in their journal). And that should tide us over until we can do some bigger fixes on the date parsing.

Oh, just a note that the latest master is v2.0.1 (which followed v2.0.0/v2.0-rc4), so rc3 is two versions old now.

**Comment by wren** [comment]
@notbalanced I just realized what you meant about rc3. That isn't the official version number in that file. We have a fix to track the version number automatically in v2.1, but are trying to get out a few bug fixes first for v2.0 (since it's a pretty big change to our dependency system). So, you are probably running the latest, if you've pulled from master lately.

**Comment by notbalanced** [comment]
@wren I just pulled the latest from master, but jrnl --version reports 2.0.0-rc3.
Could we change the logic to something like:
`if len(date_str) <= 6 and date_str.isdigit()` ?
That would exclude all of the 3 letter weekdays so they'd still be parsed correctly. It would handle bracketed pure numbers, if that is what a markdown footnote is.

**Comment by wren** [comment]
The problem is that markdown footnotes aren't just numbers. They're most commonly in the form of `[1234]` and `[abcd]`. So `[mon]` is still a valid footnote ([examples](https://stackoverflow.com/editing-help#links)). So is `[monday]` technically, but we're trying to balance the two concerns here.

**Comment by notbalanced** [comment]
Ok, I've looked at this a little closer. There are a few scenarios here:

1. Create a new entry using a day of the week as the date: `jrnl mon: Today it rained.`

2. Display entries using the `-from`, `-to`, or `-on`: `jrnl -from tue`.

3. Parsing/displaying entries that have embedded markdown footnotes (possibly using text/digits). The example given in the original issue #614:

   ```
   [2019-07-08 05:42] Entry with parse error
   ​```
   [1] pry(main)> puts "Hello, Ruby!"
   Hello, Ruby!
   => nil
   ​```
   
   [2019-07-08 05:42] Markdown link works without error
   A markdown sentence with link [elsewhere][1].
   
   [1]: http://example.com
   ```

For the first 2 cases, you want the 3 letters to be parsed as a date/time and used to create or find entries.

For the 3rd case, you have a bracketed glob that you **don't** want to be treated as a date. The [regex](https://github.com/jrnl-org/jrnl/blob/b1680fd90b7e5f03a23d997c9651d6301f577bda/jrnl/Journal.py#L121) that picks out the bracketed dates will only find a bracketed field `[ ]` when it is at the beginning of the line **AND** has a space behind it. 

The [examples](https://stackoverflow.com/editing-help#links) that you mentioned had footnoted at the end of the line, and the foot note below after it, so it wouldn't get picked up either:
```
Here's my text that won't get detected [up][mon].

[mon]: By the regex.
```
Neither of those would get picked up by the regex. And in fact the failure really isn't a markdown footnote, but a code string with a bracket number at the front:

   ​```
   [1] pry(main)> puts "Hello, Ruby!"
   ```

All this to say, I think my proposed solution, 
`if len(date_str) <= 6 and date_str.isdigit()`, 
will work even with markdown footnotes.  You would have to come up with a edge case like the following to cause it to convert `[mon]` to a new entry:

```
[2019-08-14 12:03] Text here.
This is my entry.[Valid footnote][tue]

[mon] I don't know why this would be here. It isn't a foot note.

[tue]: Here's my real foot note.
```

And it would be worth it to have the first 2 scenarios above work properly.

What do you think?

**Comment by wren** [comment]
First of all, thank you for doing this. I appreciate the effort, and the in-depth look.

I think you have a very good point about the space after. I remember putting that there to help handle the colon that usually comes after footnotes. And I think you're right that that might be enough to handle this case, and am inclined to go with your solution.

Since we're dealing with user data, though, I have to ask: can you (or anyone else) think of any reason whatsoever that anyone might have any date-like text in brackets at the start of a line followed by a space?

**Comment by MinchinWeb** [comment]
@wren Two come to mind:

1. At the end of entries added after the fact, I'll add a note as to when they were added. So a line like `[Entry added 2019-09-27]` (ok, this one probably doesn't make your criteria above..., but it has caused me issues previously).
2. When dates are used as part of the footnote identifier. When you have a markdown document (such as a single markdown file export of your whole journal), you can't have repeated footnote identifiers (or your footnotes do weird things), and so an easy solution I've used to to preface the "normal" with the date of the entry. So I have a bunch of footnote ids like `[20190927-1]`, `[201909272]`, or `[20190927a]`.

**Comment by notbalanced** [comment]
I don't see how to fix this issue with markdown footnotes and other bracketed entry contents without going to something like #630 **Strict Date parsing** where there is more rigor in the date parsing. 

However, by adding another parameter to `time.parse()`, you can flag entries that come from brackets vs. on the command line as `-to -from -on` parameters and new entries (which is the original issue above.)

**Comment by wren** [comment]
@notbalanced I think that seems like a reasonable approach until we get to implementing #630, which is the longer-term fix.

**Comment by notbalanced** [comment]
PR #665

**Comment by wren** [comment]
@notbalanced Thank you! I'll take a look at the PR in the next few days.
