### ISSUE TITLE
Documentation revamp

### ISSUE THREAD

**Issue by dvyrthu** [jrnl-org/jrnl#666]
Jrnl needs a documentation revamp. A man page would be nice, but either the website should be updated to the most recent version of jrnl or a more comprehensive README.md should to be a high priority item.

On another note, does anyone know exactly how to use the Template feature (referenced in the config for v2.0.0)?

**Comment by kcallis** [comment]
I was just about to make a suggestion about a man page. I am kind of old school and while I enjoy doing everything in markdown, sometimes, it is nice to have a nice man page to fall back for directions!

**Comment by wren** [comment]
@dvyrthu Hi! Thanks for submitting an issue. If you look at our [roadmap](https://github.com/jrnl-org/jrnl/milestones?direction=asc&sort=title&state=open), you'll see that we have a documentation revamp coming soon. To be fair, you had no way of knowing where our roadmap is, because we need to update our documentation to tell you where our roadmap is. But we are working on it. In the meantime, please feel free to send us PRs for any changes to the docs that you see. 

As for the man page (cc: @kcallis), it's an idea I like. Since jrnl is specifically a command line tool, it seems to me in the spirit of the project to have the basic documentation also available on the command line. We do have to redo the rest of our documentation first, though, since we don't know what needs to be updated yet. But I'm very open to adding a man page once we're in a place to do it right.

**Comment by wren** [comment]
Oh, for the template entry in the config, that's for export templates. That's not quite ready for primetime, but feel free to check out the repo and look at [`template.sample`](https://github.com/jrnl-org/jrnl/blob/master/jrnl/templates/sample.template) for an example of what that will look like.
