### ISSUE TITLE
Refactor CLI code

### ISSUE THREAD

**Issue by pspeter** [jrnl-org/jrnl#707]
The current CLI implementation is quite poor from a software engineering perspective. There's a long `run` function that does various things depending on which of several booleans is active. It is difficult to add or change anything in this function without accidentally breaking another part 200 lines down (as has happened e.g. in #626). 

The cli.py also contains other random functions like encrypting and decrypting that really shouldn't be there. 

I propose refactoring out the run function into multiple distinct functions or even separate modules. The "mode" booleans already provide a hint of which four pieces of functionality jrnl currently supports: 
 - Composing new entries
 - Viewing old entries
 - Exporting 
 - Importing 

Now, I don't want to change the way you actually interact with poetry (i.e. I don't want to add for example a `poetry compose` command) even though that would simplify the code a bit. However, implementing each functionality in a separate function and having something like the current `cli.guess_mode` calling one of them would already make things a lot clearer.

**Comment by wren** [comment]
This work seems like it would go well with the refactoring we'll have to do to allow users to update their config, so I'm putting it in that milestone for now. As we get closer, and get a better idea of the work entailed, that might change a bit.

This is work that I was considering down the line (after the current milestones), in order to pave the way for import/export plugins, but if anyone has time to do it sooner, I wouldn't turn it away.

**Comment by wren** [comment]
We're also looking into using the Click library for this refactor.

**Comment by wren** [comment]
Click library ticket: #866
