### ISSUE TITLE
Export code is a mess

### ISSUE THREAD

**Issue by pspeter** [jrnl-org/jrnl#713]
The export.py file is currently not used at all. You can't even import it because it tries to import a package that was moved somewhere else. Do we still need this code? 

Also, the template export code is some of the most confusing code I've ever read. Part of the templates seem to be parsed as yaml, which then updates some class variables, there's random classes being constructed using type(), custom template parsing logic using regex... I don't think this is maintainable in the long run. Some of it even seems to break in 3.8, at least Travis doesn't like it (see #710). We should think about completely replacing this part imho.

**Comment by wren** [comment]
@peter-schmidbauer Yup! Totally agree about the template code. @micahellison and I thought about removing it a while back, but ultimately settled on leaving it for the time being because it didn't seem like it was affecting anyone that wasn't using it. With the issues coming up during your PR, though, I'm inclined to remove it earlier than later. 

I really wish we had better data about how many people use some of these features, though. It's not ideal if we oscillate between removing something, only to adding it back after users complain. Do you think it's possible to work around it for now? Or is that too much extra work?

Also, the export.py also seems good to get rid of to me, too.

**Comment by peter-schmidbauer** [comment]
I'm not sure why the test is failing on 3.8 on travis tbh, I can't replicate that error on my machine. 

I can't image a whole lot of users used the templating feature to be honest, but we don't even have to remove it necessarily, rewriting would be another option. The templating part looks similiar enough to [jinja2](https://jinja.palletsprojects.com/en/2.10.x/) that we can probably just replace it with some simple calls to that and remove most of the "weird" code. Keeping 100% backwards-compatibility will probably be impossible but it's probably close enough. First step - if we go down that route - would be to write some thorough tests for it though, currently the whole is tested by only like four test.

**Comment by wren** [comment]
Keep for now.

**Comment by stavshamir** [comment]
Hi, I'm trying to use the custom template feature, unsuccessfully (#813). I'd be glad to try and take over some of the export code as discussed above.

**Comment by dbxnr** [comment]
@stavshamir Take a look at `/plugins/text_exporter.py` - it has a few generic write methods and is behind extended by all the current export plugins.

`export.py` seems to be completely superfluous and could probably be safely removed...

**Comment by wren** [comment]
@stavshamir PRs are always welcome. The above all should have the details you need, but if you have any questions about implementation, please ask here. 

Thank you for taking this on!
