### ISSUE TITLE
Add Python 3.8 support

### ISSUE THREAD

**Issue by pspeter** [jrnl-org/jrnl#739]
I tried adding travis tests for 3.8 before in #710 but they failed for some reason, so for now I just added them for 3.6 and 3.7. We should add 3.8 support ASAP though.

**Comment by wren** [comment]
The test suites are now running 3.8 (linux, mac, and windows). They're under the "Allowed Failures" section for now, but we should figure out what's up with 3.8 (which is failing consistently across all platforms).

**Comment by mathematicalmichael** [comment]
> The test suites are now running 3.8 (linux, mac, and windows). They're under the "Allowed Failures" section for now, but we should figure out what's up with 3.8 (which is failing consistently across all platforms).

just an FYI: I didn't pay attention to the dependencies and ended up building a docker image based on alpine python 3.8.1 and jrnl 2.1.post2 (via pip) and haven't had any trouble with it. I went through the changelog and saw that 3.6+ support only comes in 2.1.1 and thought it was worth checking out what I have been using.

https://github.com/mathematicalmichael/docker-env/blob/master/jrnl/Dockerfile was last built Jan 20 and I've been relying on it since.
