### ISSUE TITLE
Wrong password 3 times after closing editor results in loss of all changes

### ISSUE THREAD

**Issue by wren** [jrnl-org/jrnl#799]
** Current behavior **
After closing your editor (either a new entry or editing an old one), if you have an encrypted journal, you are prompted for your password. If you enter the correct password, your entry is saved and everything is fine. If you get the wrong password, you are re-prompted up to a total of 3 times. If you get the password wrong all 3 times,  you see `Extremely wrong password.` message, and jrnl quits.

The problem with this is that the temp file has already been deleted by the time you are prompted for your password, so you lose all changes.

**Expected behavior**
Since there's no risk of leaking encrypted data at this point in the flow, we should reopen the editor for the user and give them a chance to do something with the data they were just working on.

**Comment by ollybritton** [comment]
Hi, just wondering if any progress have been made on this? I was about to file a bug report for the same behavoir but it appears it already exists in four different places: this issue, #270, #256 and #284. I don't mind attempting to submit a pull request though I haven't contributed yet and don't have that much experience with open source.

I'm currently using the workaround of creating a new entry with the `jrnl` command, writing some placeholder text that I don't mind potentially losing, exiting and then inputing the password so it saves. I then call `jrnl -n 1 --edit` so that it asks me for the password first and ensures that whatever I write will be saved but this isn't ideal.

**Comment by wren** [comment]
I don't think anyone has been working on this one yet. I'm happy to look over a PR if you send one over. Please look at CONTINUING. md for notes on how to get set up to contribute.

And you're right that this seems like a regression. Not sure when it happened, but we'll need to make sure to add tests to prevent it from happening again.

**Comment by wren** [comment]
I think PR #951 is a good patch for this. In the longer term, I would like to move the password prompt after the edit again, and just kick the user back to the editor if they get the password wrong 3 times. I think the smoothness of being able to open an editor immediately and start typing is worth a lot, and would like to keep that.

Of course, data loss is bad, so we'll move the password prompt for now.
