### ISSUE TITLE
Using jrnl with emacs?

### ISSUE THREAD

**Issue by wakatara** [jrnl-org/jrnl#858]
Hola jrnl users,

OSX 10.15.3 (and also Solus Linux 4.1 budgie)
Jrnl 1.9.8
Installed via homebrew
emacs 26.3

I'm trying to edit journal entries in emacs and then have them saved back into a password protected jrnl file. While I do have a simple function that can simply pipe things to the jrnl command from the buffer, that will not work password protected. While I see examples for vim (what I have been using) and sublime and such, I don't see anything for emacs.

(and yes, before you mention it, I do know about emacs org-journal. I use it for logging but want a separate, encrypted journal for my personal thoughts and am not a huge fan of DayOne since it moved on from version 1 (which I thought was better... =] )..

(Ideally some day, I would love a minor emacs mode that allows me to search, edit and submit entries back into jrnl though I think that might be asking a much =] . As an example of a cli program that does this, check out the ledger-mode for emacs if you're curious. It is super handy.).

**Comment by micahellison** [comment]
I'm not an emacs user so caveat emptor, but you should be able to configure jrnl to use emacs by modifying the `editor` field of your config file to point to emacs. That config file should be in your `~/config/jrnl/` directory. Once it's set, jrnl will open up emacs to a temporary file whenever you edit entries or create entries. When you close emacs, jrnl prompts you for your password and saves the entry to your journal.

**Comment by wren** [comment]
@wakatara Also, if you want to update to v2.2 (available via homebrew), you'll get a lot of improvements. Specifically related to this issue, v1.9.8 had a bug in how it parsed the editor field which made it impossible to pass certain types of parameters to the editor. I personally had a lot of difficulty configuring neovim at the time. The bug has since been fixed. 

Anyway, for the config itself: usually, the key to getting an editor to cooperate is having it wait before handing control back to the cli process. Usually, this is in the form of a flag (like `--wait` or whatever), but I don't know what that looks like for emacs.

Please report back if you find how to do this, and we'd love to add it to the documentation.

(Also, I'm personally all for integrations with editors like emacs. We don't really have the time or knowledge to pull this off ourselves, but I'd be happy to give a shoutout to a sister project that integrates jrnl.)

**Comment by wakatara** [comment]
Hey there guys!

I upgraded and can confirm this is working with emacs now. The opnly bugbear is that it launches an entire new instance of emacs (which is not the lightest weight editor around) rather than opening the file withing an existing emacs that is already open. This might be simply a quirk of the fact I'm using an OSX version of emacs rather than something that uses emacsclient and merely opens a window on the backend process. 

However, feels like this can be closed as working. Thanks!

**Comment by xeruf** [comment]
btw, the timestamp format is fully compatible with org-mode and org also highlights the tags, so it is quite handy to use that as major-mode there
