### ISSUE TITLE
(AUR) Incompatibility with tzlocal 2.0.0 or packaging mistake?

### ISSUE THREAD

**Issue by StanczakDominik** [jrnl-org/jrnl#883]
I've tried tried the following both in a conda env via pip and via the AUR package on Arch Linux, in the system Python environment.

On launching `jrnl` installed with the system Python and current `tzlocal`, I'm getting this error (which I'm copypasting from https://aur.archlinux.org/packages/jrnl/, as I've since moved to running `jrnl` through `pipx`):

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (tzlocal 2.0.0 (/usr/lib/python3.8/site-packages), Requirement.parse('tzlocal<2.0,>=1.5'), {'jrnl'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/jrnl", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3255, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3238, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3267, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'tzlocal<2.0,>=1.5' distribution was not found and is required by jrnl
```

I don't see why `tzlocal 2.0` would be incompatible with `jrnl`, so I'm guessing this is probably a packaging issue! Otherwise, I'll be happy to run this through pipx.

I tried digging through the setup files (`pyproject.toml`, I presume?), but I haven't been able to find anything explicitly preventing version 2.0 of tzlocal from working.

**Comment by SpyrosRoum** [comment]
When I installed from the aur I had the same issue but then I uninstalled that version and I tried with pip and that fixed it

**Comment by StanczakDominik** [comment]
Could you please check the version of tzlocal you ended up with? I suspect pip just got you version 1.5 (IIRC that's the latest pre 2.0 version).

**Comment by SpyrosRoum** [comment]
python-tzlocal is at version 2.0 from pacman

**Comment by StanczakDominik** [comment]
Okay then, that's pretty weird and I don't get what's going on. I'll be doing some more tests on this and I'll close the issue if it turns out it's a packaging issue on the AUR side.

**Comment by wren** [comment]
@StanczakDominik Does the regular pipx install work for you? Is it only the AUR installation that shows this? I can't repro on my machine, and we've had troubles contacting the AUR side of things to keep that package properly up-to-date.

**Comment by SpyrosRoum** [comment]
I had the issue when installing from aur. After that I uninstalled from aur, installed with pip and it worked fine

**Comment by micahellison** [comment]
I see this issue is being addressed in the comments of the [jrnl AUR package](https://aur.archlinux.org/packages/jrnl/), and I appreciate that the someone has mentioned the pipx workaround there.

While none of jrnl's maintainers are Arch users, we'd be happy to coordinate with anyone working on this package to keep errors like this from happening. Feel free to reach out to us if you have any questions or ideas.

**Comment by benoliver999** [comment]
I get the same thing and clocked this line:

    pkg_resources.ContextualVersionConflict: (tzlocal 2.0.0 (/usr/lib/python3.8/site-packages), Requirement.parse('tzlocal<2.0,>=1.5'), {'jrnl'})

Would changing the dependency to 2.0.0 instead of 2.0 work?

**Comment by eli-schwartz** [comment]
> I don't see why `tzlocal 2.0` would be incompatible with `jrnl`, so I'm guessing this is probably a packaging issue! Otherwise, I'll be happy to run this through pipx.
> 
> I tried digging through the setup files (`pyproject.toml`, I presume?), but I haven't been able to find anything explicitly preventing version 2.0 of tzlocal from working.

This is an upstream issue in this repository as seen right here:

https://github.com/jrnl-org/jrnl/blob/5d44997c387f655f80ea3665fcf79f281088ac2c/pyproject.toml#L26

Due to this metadata, the pkg_resources entry point will look at a distribution-installed system, see that tzlocal 2.x (the latest, preferred version) is installed, and note that jrnl asserts to be incompatible with these new tzlocal versions.

The pkg_resources entry point then says "I refuse to start the program out of fear that it might not work".

The solution is pretty simple: the upstream jrnl project should not use overly-restrictive version pinning if they have no reason to think there is a problem. Unfortunately, due to the ill-conceived choice to use poetry, they have been encouraged to use wild nodejs version pinning -- `^1.5` means "greater than 1.5, but less than 2", the full version constraints in the current PyPI release look like this:

```
install_requires = \
['ansiwrap>=0.8.4,<0.9.0',
 'asteval>=0.9.14,<0.10.0',
 'colorama>=0.4.1,<0.5.0',
 'cryptography>=2.7,<3.0',
 'keyring>=19.0,<20.0',
 'parsedatetime>=2.4,<3.0',
 'passlib>=1.7,<2.0',
 'python-dateutil>=2.8,<3.0',
 'pytz>=2019.1,<2020.0',
 'pyxdg>=0.26.0,<0.27.0',
 'pyyaml>=5.1,<6.0',
 'tzlocal>=1.5,<2.0']
```

pipx is *NOT* a solution, because that is just saying "pip install it into a virtualenv and have it install an old tzlocal release in the process".

This bug report was incorrectly closed, there is nothing to be addressed by AUR packaging.

**Comment by eli-schwartz** [comment]
@wren, @micahellison,

if the jrnl project wishes to pin exact versions of your dependencies in your pyproject.toml, it would make sense to regularly update those, rather than sticking with year-old pinned versions of your dependencies.

**Comment by micahellison** [comment]
Thanks for investigating and explaining this, @eli-schwartz. I'm not sure why the versions were set to be so restrictive at first. Maybe concerns around major releases breaking compatibility? @maebert this looks like your code -- any thoughts on this?

Whatever the case, all tests are passing on my environment with tzlocal 2.0, so I'll start with a PR to unpin that library.

**Comment by eli-schwartz** [comment]
> I'm not sure why the versions were set to be so restrictive at first. Maybe concerns around major releases breaking compatibility?

Because if you use `poetry add some-dependency` then the poetry documentation states the following:
> If you do not specify a version constraint, poetry will choose a suitable one based on the available package versions.

Which means poetry will just magically add a random pin.

**Comment by micahellison** [comment]
We'll be reviewing newer releases of jrnl's dependencies more closely in the future, though we're still going to restrict their maximum versions to each current major release. I think that's a reasonably cautious approach, especially for a program such as jrnl that handles such potentially sensitive data. So in the meantime, I'm restricting tzlocal to >1.5 and <3.0.

**Comment by wren** [comment]
For anyone reading this coming from AUR: we'd still like to get ahold of whoever is maintaining the jrnl listing there. There are packaging mistakes (like the one from this ticket). Please contact us so we can prevent issues like these.

We'll continue to do what we can to help users as we get reports, but the best approach for everyone is to get the AUR package properly working with our dependencies.

**Comment by flocomkoko** [comment]
Hi I am packaging the AUR, just got a comment about it. 
Could you point me to my mistake in packaging? 
I am open to all suggestions since i am very new to the AUR and this is my first package I took over since the original maintainer orphaned it and i wanted to have the new version on my system.

If you are interested in maintaining yourself i would hand the package over to you.

**Comment by wren** [comment]
@flocomkoko No worries, and thank you for reaching out! Can we take the conversation into our issue for AUR (#783)? I'll comment on there to continue this.

**Comment by wren** [comment]
And again for anyone coming here from old links: jrnl has since been added to the official package repo (https://archlinux.org/packages/community/any/jrnl/), so you should be able to install jrnl not from AUR. But please file an issue if you have any problems!
