### ISSUE TITLE
Syntax problems aren't caught by current testing

### ISSUE THREAD

**Issue by wren** [jrnl-org/jrnl#889]
## Bug report

A bug came in recently (#878) that was a simple syntax issue. We should have caught this, but it slipped into a release. We have a patch already in the works, but I'm starting this issue to come up with an approach for preventing these types of problems from getting into releases in the future.

Maybe it's as simple as adding a linting step to our tests. If this were the case, I'd want it to be strict enough to catch syntax problems, but not so strict as to frustrate contributors with nit-picky suggestions.

**Comment by mlcdf** [comment]
Hello Jonathan,

I stumble upon this issue by accident, but since I've been investing linters for Python at work, I thought I might as well share my thoughts with you.
I think something like `pyflakes` would do the job just fine.

I retrieved the code to before the fix for #878 and I run `pyflakes` :
```
[maxime@nepture jrnl]$ time pyflakes jrnl/
jrnl/install.py:4: 'getpass' imported but unused
jrnl/install.py:10: '.Journal.PlainJournal' imported but unused
jrnl/install.py:11: '.EncryptedJournal.EncryptedJournal' imported but unused
jrnl/FolderJournal.py:5: '.Entry' imported but unused
jrnl/__init__.py:3: 'os' imported but unused
jrnl/EncryptedJournal.py:13: 'typing.Optional' imported but unused
jrnl/Journal.py:4: '.util' imported but unused
jrnl/time.py:60: use ==/!= to compare str, bytes, and int literals
jrnl/plugins/yaml_exporter.py:5: 'os' imported but unused
jrnl/plugins/jrnl_importer.py:5: '..util' imported but unused
jrnl/plugins/jrnl_importer.py:18: local variable 'old_entries' is assigned to but never used
jrnl/plugins/markdown_exporter.py:5: 'os' imported but unused

real	0m0,215s
user	0m0,192s
sys	0m0,022s
```
As you can see, it's crazy fast, and I would have caught the error in `time.py` (plus others things).
One thing to note thought, it only parses the source files, it doesn't note import them (that why it's so fast).

While investigating, I noticed that the Makefile already as a "lint" entry using `flake8`, but it's not used in the CI.
Since `flake8` use `pyflakes` amongst other libs, the following is similar to the command I run above :
```
[maxime@nepture jrnl]$ flake8 jrnl/ --select F 
jrnl/install.py:4:1: F401 'getpass' imported but unused
jrnl/install.py:10:1: F401 '.Journal.PlainJournal' imported but unused
jrnl/install.py:11:1: F401 '.EncryptedJournal.EncryptedJournal' imported but unused
jrnl/FolderJournal.py:5:1: F401 '.Entry' imported but unused
jrnl/__init__.py:3:1: F401 'os' imported but unused
jrnl/EncryptedJournal.py:13:1: F401 'typing.Optional' imported but unused
jrnl/Journal.py:4:1: F401 '.util' imported but unused
jrnl/time.py:60:8: F632 use ==/!= to compare str, bytes, and int literals
jrnl/plugins/yaml_exporter.py:5:1: F401 'os' imported but unused
jrnl/plugins/jrnl_importer.py:5:1: F401 '..util' imported but unused
jrnl/plugins/jrnl_importer.py:18:9: F841 local variable 'old_entries' is assigned to but never used
jrnl/plugins/markdown_exporter.py:5:1: F401 'os' imported but unused
```
The thing is, since Black is also used, there's no need for the part of flake8 that check the style of the code (which is `pycodestyle`). 

Here's what I propose : replacing flake8 by pyflakes, and running the lint task in the CI.
> in the Makefile
```
lint: ## pyflakes
	poetry run pyflakes .
```

> in the travis.yml
```
  include:
    - name: Lint, via Black
      python: 3.8
      script:
        - black --version
        - black --check . --verbose --diff
        - make lint

```

Another option is to use `Pylint`, with is a lot more powerful, but also a lot slower and requires a lot of tuning so I doesn't get in your way.

What's your thought on this?

**Comment by wren** [comment]
@mlcdf Thanks for the response! This is very good information.

You're right that we haven't been using flake8, and what you mention about using black is exactly the correct reason why. I'm hesitant to reintroduce flake8 because I really don't want to overburden contributors with nitpicky feedback from a too-strict linter. And Pyflakes sounds like it might meet our needs.

Thank you!

**Comment by wren** [comment]
@micahellison What do you think?

**Comment by micahellison** [comment]
I love it! I think we should apply this to our build process, and fail the build if it fails. If it gets to be too stringent, we can always dial it back.

**Comment by MinchinWeb** [comment]
c.f. #770

**Comment by MinchinWeb** [comment]
I created a Pull Request (#911) to do this, largely based on mlcdf's suggestions. However, I've set up Travis to call `pyflakes` directly (rather than though a make file) as this provides better cross-platform support. Also, I've made it a separate test of Travis, so it should be clearer why a Pull Request is failing.
