### ISSUE TITLE
"jrnl --delete something" deletes all journal entries

### ISSUE THREAD

**Issue by justdoit176** [jrnl-org/jrnl#932]
## Bug report

* **Please tell us about your environment:**
  - Jrnl version: (run `jrnl -v`)
  jrnl version v2.4

  - How you installed Jrnl
  pip install --user -U jrnl
  (previous version: 2.2, installed with pip)

  - Operating system [MacOS, Linux, Windows?]
  Linux openSUSE Tumbleweed

* **What is the current behavior?**
  Add some entries to a journal, try to delete an entry setting a filter, say a string. Even if you don't delete any entry when prompted, only the entries that match the filter will be preserved in the journal. **ALL the other entries will be deleted**.

* **Please provide the steps to reproduce and if possible a minimal demo of the problem**
  `$ jrnl Just a test`
[Entry added to default journal]

  `$ jrnl Another test`
[Entry added to default journal]

  `$ jrnl "Don't delete me"`
[Entry added to default journal]

  `$ jrnl -n 5`
  2020-05-02 17:12 Just a test

  2020-05-02 17:13 Another test

  2020-05-02 17:13 Don't delete me

  `$ jrnl --delete nothing`

  `$ jrnl -n 5`

  `$ `

* **What is the expected behavior?**
   The "--delete" option should only delete the selected entries.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

  Every time I execute `jrnl --delete something` the only content of the journal file become a single line like this:
  `gAAAAABerY4t0dY_yIR4XMot62Aw7cFDIbNExvnCL9TXbLbUpjNA0yQo1nVBJ6yPl0CnN3OAs4cLVB4ePiYN-V2EnGDzkZ6_ng==`
  It changes every time I execute the command.

**Comment by wren** [comment]
Confirmed on:
jrnl v2.4
macos 10.15
python 3.8.0


Working on this right now. Expect a patch soon.

**Comment by wren** [comment]
So, the reason for this is that in `jrnl --delete something`, "something" is actually a search for a tag. Since "something" isn't a valid tag that exists in any entry, the search returns no results. No results means the delete functionality doesn't prompt the user for anything (since it prompts once for each search result).

The problem occurs after this when the results are then written back to the journal. The entries shouldn't be written, because there are none. This is what deletes the entries in the current journal.

The fix should be to check if the search is empty, and not execute the write. It would also be good to output a message to the user to tell them why no entries are being deleted. Also, we should expand our tests to account for possible empty results for each potential filter.
