### ISSUE TITLE
jrnl tags-to-sabre/dav - ICalendar feature

### ISSUE THREAD

**Issue by 50ten40** [jrnl-org/jrnl#943]
## Feature Request

Hello! Thank you for reporting an issue!
If you would fill out the below points, that would make our process a whole lot easier!

* **What is the motivation / use case for changing the behavior?**
feature to push jrnl tags to sabre/dav without intervention if config has dav server entry

* **Please provide examples of the usage**
add a dav tag to jrnl entry '@todo by 'date' or '@event' with '@user by date' in jrnl entry and feature pushes to sabre/dav.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
I have a project page here. https://github.com/Durastudio-FLOSS/jrnl-rific.

**Comment by micahellison** [comment]
We've been discussing application hooks (#921) which sound like a good way to implement what I understand this feature request to be asking for.

Instead of jrnl implementing a wide variety of export protocols in its core code, you'd have the opportunity to allow it to execute custom scripts after certain events, such as when you finish new entries.

**Comment by 50ten40** [comment]
This makes sense. Thank you.
