### ISSUE TITLE
Update or remove docs on readthedocs

### ISSUE THREAD

**Issue by sixhobbits** [jrnl-org/jrnl#977]
## Feature Request
- Update or remove the docs at https://jrnl.readthedocs.io/en/latest/advanced.html

### Use Case/Motivation
I spent a while trying to figure out why stuff I add to `~/.jrnl_config` was being ignored. These docs are marked 'latest' and still talk about this instead of the new .yaml file in v2. It's not obvious that these docs are for an older version if you land on that page directly.

If the new docs are hosted on jrnl.sh directly, the readthedocs ones should maybe redirect there? Or be updated if they are still active too.

**Comment by guydebros** [comment]
I've started sprucing up the documentation (it's something I can help with as a non-programmer), but haven't had the time to really dig into it.

There's also a documentation section at the main site (https://jrnl.sh) but it's also out of date. I think it shows the same thing that readthedocs shows.

Is there a way to auto-update when changes to the `.md` files are pushed to the main repository? Or did it not update because I was on the `develop` branch?

**Comment by eshrh** [comment]
Yeah, the docs are quite out-of-date. Also missing are details of how each of the exporters work.  

I'm not sure how the documentation gets updated. Your changes for usage.md were pushed to master 10 days ago or so, but they're not on the website...

**Comment by micahellison** [comment]
My apologies for jrnl.sh being a few weeks out of date. We haven't yet incorporated the documentation deployment process with the automated release process, so sometimes we forget this step. I'm deploying it now.

I don't know what the story is with readthedocs.io though. It looks like it hasn't been updated since jrnl was migrated to an org on github. Maybe it's something set up by the original founder. I'll try to contact some folks involved to see if we can get it synced up.

**Comment by sixhobbits** [comment]
Thanks all. Shout if I can help with anything.

**Comment by guydebros** [comment]
@micahellison does it make sense to have docs in two places? More things to update, more things to break...

**Comment by eshrh** [comment]
Probably the export page, https://jrnl.sh/export/

**Comment by guydebros** [comment]
🤦‍♂️

**Comment by micahellison** [comment]
readthedocs.io is nice because it has versioned documentation. jrnl already has two very different versions and I can imagine that users might appreciate being able able to go back to see how the old one worked, especially if there's any data recovery they need to do.

However, @wren and I have been working on getting readthedocs to work and we're running into one roadblock after another. For some reason it appears to be using mkdocs 0.17 to build our documentation instead of mkdocs 1+ like it says it should. Even when we added a `readthedocs.yml` config file, [it still failed](https://readthedocs.org/projects/jrnl/builds/11249030/).

I'm not sure what our next steps are. Maybe we'll come back this in a bit, but if we can't find a solution, we should probably get rid of it since it is confusing to have that old documentation up as if it's the official documentation.
