### ISSUE TITLE
Import/Export docs have no Import information

### ISSUE THREAD

**Issue by bjornasm** [jrnl-org/jrnl#995]
### Environment
Docs on jrnl.sh

### Current Behavior
The docs header is import and export, however they don't show any example on import at all.

**Comment by wren** [comment]
Yup, this is absolutely right. The page referenced is here: https://jrnl.sh/export/

Here's some notes for what needs to go into this section if anyone feels like sending over a PR:

- `jrnl firstjournal --export text | jrnl secondjournal --import` lets you import from one journal to another.
- You can also use any filters like you would normally, like `jrnl -4 -contains "some text" -starred --export text | jrnl secondjournal --import`.
- Just like the rest of journal, specifying the journal is optional, and will use the journal `default` if one isn't given. So, `jrnl --export text | jrnl secondjournal --import` sends entries from journal `default` to journal `secondjournal`.
- You can import directly from a file using the `-i` flag like `jrnl --import -i somefile.txt`. You can use this if you don't want to pipe the data to jrnl as shown above.
- `--import` technically supports importer plugins, but the only one we ship with is for the default jrnl format (which is equivalent of `--import jrnl`, but we default to jrnl since only one exists, by default). Some plugins might exist out there, but I haven't taken the time to look for any (please comment if you know of some).

**Comment by xeruf** [comment]
Hey, I have some text where I lost the original file, I only got the default jrnl output (with dates not in brackets and multilines using pipe) - it doesn't seem to pick that up correctly?

**Comment by wren** [comment]
@xerus2000 The default output is the "pretty" format, and is really only meant for display purposes (it has color codes, etc, that make parsing impractical). We can probably do some shell magic to fix up the pretty format to make it importable. Can you paste an example entry with the date format you use here so I can help?

**Comment by xeruf** [comment]
I fixed it manually with vim ;) but since it's not much different, it shouldn't be hard to also allow importing that automatically?

**Comment by micahellison** [comment]
I was just playing around with this today while checking out #1256, and found that `--import` doesn't import any entries that already exist in the target journal (using date, title, AND body to determine duplicates). Just wanted to point that out for when we get around to documenting this feature more fully.

**Comment by viegasfh** [comment]
I have given a try to this import feature, and it doesn't work for other journals, only the default one.

```
$ jrnl personal --import -i workspace/jrnl/journal.txt
[13 imported to default journal]
```
It always gets imported to the default journal and not the one I am pointing out, which should be personal in this case.

**Comment by micahellison** [comment]
> I have given a try to this import feature, and it doesn't work for other journals, only the default one.
> 
> ```
> $ jrnl personal --import -i workspace/jrnl/journal.txt
> [13 imported to default journal]
> ```
> 
> It always gets imported to the default journal and not the one I am pointing out, which should be personal in this case.

It does work on non-default journals, but it doesn't work on directory journals. We have a bug filed for this in #999.
