### ISSUE TITLE
Add `template` keyword to advanced documentation

### ISSUE THREAD

**Issue by cguess** [jrnl-org/jrnl#997]
## Bug Report

`template` option is not documented at https://github.com/jrnl-org/jrnl/blob/develop/docs/advanced.md, though it is in https://github.com/jrnl-org/jrnl/blob/develop/docs/recipes.md

I'm brand new to this community, and thank you for a wonderful project. While setting up this morning (with a *very* specific use case in mind) I noticed that the `template` options is missing from the config documentation.

I would issue a PR fixing this myself, but being brand new to using this I don't want to submit something horrible incorrect.

Thank you for this wonderful project!

**Comment by wren** [comment]
Hi, @cguess. Thanks for reporting the issue! We definitely should update that section to include more info about templates. In the meantime, if you have any questions for your use case, feel free to ask and we'll help you as best we can.

For contributing, we'll help you along with any PR, so don't worry too much about it being wrong. Just give our [contributing doc](https://github.com/jrnl-org/jrnl/blob/develop/CONTRIBUTING.md#editing-documentation) a read about editing documentation, and you'll know all of our guidelines.

**Comment by startakovsky** [comment]
I agree with the above. There is writing in the `recipes` part of the documentation that literally says "the other way is to use the configuration file and put in a path wrapped in double quotes to your template file".  But the thing that continues to remain unclear is "then what".... because `jrnl > template.txt` doesn't do anything when not in the template folder.... 🤷
